name: fibali
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.24+90
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  agora_rtc_engine: ^6.3.0
  animated_text_kit: null
  app_settings: ^4.2.0
  app_version_update: ^2.0.3
  audioplayers: ^5.2.1
  badges: null
  cached_network_image: ^3.2.0
  carousel_slider: ^4.2.1
  chips_choice: ^3.0.0
  circle_flags: ^3.0.1
  cloud_firestore: null
  cloud_functions: null
  connectivity_plus: null
  currency_picker: ^2.0.16
  darq: ^1.1.1
  device_info_plus: ^9.0.1
  envied: null
  equatable: null
  extended_image: ^8.2.0
  faker: ^2.0.0
  file_picker: ^5.3.3
  filter_list: ^1.0.2
  firebase_analytics: null
  firebase_app_check: null
  firebase_auth: null
  firebase_core: ^2.26.0

  firebase_dynamic_links: null
  firebase_messaging: null
  firebase_remote_config: null
  firebase_storage: null
  firebase_ui_firestore: null
  firebase_ui_future_firestore:
    path: modules/firebase_ui_firestore-1.5.4
  flamingo: ^3.0.0
  flamingo_annotation: ^1.0.0
  flex_color_scheme: null
  fluentui_system_icons: ^1.1.186
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_circular_text: ^0.3.1
  flutter_easyloading: null
  flutter_form_builder: ^9.1.1
  flutter_launcher_icons: null
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_login:
    path: modules/flutter_login
  flutter_markdown: ^0.6.14
  flutter_rating_bar: ^4.0.0
  flutter_ringtone_player: ^3.2.0
  flutter_spinkit: null
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: null
  fluttericon: ^2.0.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: null
  form_builder_validators: ^9.1.0
  gap: ^3.0.1
  geocoding: null
  geoflutterfire2:
    path: modules/geoflutterfire2-2.3.13
  geolocator: null
  get: ^4.6.6
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.3.0
  google_nav_bar: ^5.0.5
  google_sign_in: ^6.0.2
  http: null
  hydrated_bloc: ^9.1.0
  iconify_flutter:
    git: https://github.com/AbderraoufKhodja/iconify_flutter.git
  image_picker: ^1.0.2
  intl: ^0.18.0
  intl_phone_number_input:
    path: modules/intl_phone_number_input
  intro_views_flutter: null
  just_the_tooltip: ^0.0.12
  language_picker: ^0.4.1
  logger: ^1.3.0
  lottie: ^2.1.0
  map_launcher: null
  markdown: ^7.1.0
  meta: null
  modal_progress_hud_nsn: ^0.3.0
  multi_select_flutter: null
  multiple_stream_builder: ^3.0.2
  path_provider: null
  permission_handler: null
  readmore: ^2.2.0
  reorderable_grid: ^1.0.5
  reorderables: ^0.6.0
  rxdart: null
  share_plus: ^7.0.1
  shared_preferences: null
  shimmer: null
  showcaseview: ^2.0.3
  sign_in_with_apple: ^4.3.0
  swipable_stack: ^2.0.0
  syncfusion_flutter_sliders:
    path: modules/syncfusion_flutter_sliders-20.4.43
  timeago: null
  toggle_switch: ^2.0.1
  translator:
    path: modules/translator-0.1.7
  url_launcher: null
  uuid: null
  video_compress: ^3.1.2
  ae_api:
    path: modules/ae_api
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retry: ^3.1.2
  infinite_scroll_pagination: ^3.2.0



flutter_icons:
  image_path: "assets/launcher_icon.jpg"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/launcher_icon.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  envied_generator: null
  chewie: null
  dependency_validator: ^3.0.0
  # flamingo_generator: null
  flutter_lints: null
  video_player: null

flavorizr:
  ide: "vscode"
  flavors:
    swappers:
      app:
        name: "Swappers"
        color: "blue"
      android:
        applicationId: "com.deepdev.swappers"
        icon: "swappers_1024x1024.webp"
        firebase:
          config: ".firebase/android/swappers/google-services.json"
    fibali:
      app:
        name: "Fibali"
        color: "blue"
      android:
        applicationId: "com.deepdev.fibali"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  assets:
    # - assets_web/ # for web
    - assets/
    - assets/sounds/ringlong.mp3
    - assets/60265-digital-camera.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
