import 'package:fibali/fibali_core/utils/strings.dart';

final appLocEN = {
  R.items.name: "Items",
  R.messageSent.name: "Message sent",
  R.keywords.name: "Tags",
  R.phoneNumber.name: "Phone number",
  R.province.name: "Province",
  R.subProvince.name: "Sub province",
  R.updatingStoreInfo.name: "Updating store info...",
  R.sellerReminderSent.name: "The seller will receive a reminder to send the order",
  R.invalidPhoneNumber.name: "Invalid phone number",
  R.locationUnknown.name: "Location unknown",
  R.creatingUser.name: "Creating user",
  R.quote.name: "Quote",
  R.unknown.name: "Unknown",
  R.share.name: "Share",
  R.editProfile.name: "Edit profile",
  R.addItem.name: "Add item",
  R.updateStoreInfo.name: "Update store info",
  R.logout.name: "Logout",
  R.contactInfo.name: "Contact ",
  R.from.name: "From",
  R.all.name: "All",
  R.send.name: "Send",
  R.mayBeLater.name: "MayBeLater",
  R.quantity.name: "Quantity",
  R.kickOf.name: "KickOf",
  R.search.name: "Search",
  R.magazin.name: "Magazin",
  R.price.name: "Price",
  R.comparePrice.name: "Compare price",
  R.fillDescription.name: "Please fill an item description",
  R.fillTitle.name: "Please fill item title",
  R.sellerBoard.name: "Seller board",
  R.variants.name: "Variants",
  R.addValue.name: "Add at least one value to ",
  R.nineMax.name: "Maximum of 9 attributes",
  R.editItem.name: "Edit Item",
  R.orderDetails.name: "Order details",
  R.posts.name: "Posts",
  R.camera.name: "Camera",
  R.submit.name: "Submit",
  R.alreadyReviewd.name: "Already reviewd!",
  R.saveNDefault.name: "Save and set default",
  R.missingAddress.name: "Missing delivery address",
  R.pleaseUpdateAddress.name: "Please update address",
  R.total.name: "Total: ",
  R.onlyAlgeria.name: "Only Algeria is available for now!",
  R.checkPhone.name: "Check phone",
  R.getSms.name: "Get sms",
  R.streaming.name: "When a user likes one of your items, his items will appear here.",
  R.fillOTP.name: "Fill OTP",
  R.streetAddress.name: "Street address",
  R.addStreetAddress.name: "add street address",
  R.addDeliveryAddress.name: "add delivery address",
  R.editDeliveryAddress.name: "Edit delivery address",
  R.addPhoneNumber.name: "Add phone number",
  R.updateAddress.name: "Update address",
  R.deliveryAddress.name: "Delivery",
  R.title.name: "Title",
  R.sixDigitsOTP.name: "Please input 6 digits code from sms",
  R.code.name: "Code",
  R.checkCode.name: "Check code",
  R.setting.name: "Setting",
  R.distance.name: "Distance",
  R.news.name: "News",
  R.strictSearchMode.name: "Strict search mode",
  R.oops.name: "Oops, something went wrong. Please check your network and try again.",
  R.likeItem.name: "Like item",
  R.noItems.name:
      "Seems like there no is items around, try to change or to expand your search area.",
  R.shareWithFriends.name: "or share the app with your friends and start swapping with them.",
  R.reload.name: "Reload",
  R.giveAway.name: "Give away",
  R.edit.name: "Edit",
  R.notifications.name: "Notifications",
  R.delete.name: "Delete",
  R.chat.name: "Chat",
  R.match.name: "Match",
  R.done.name: "Done",
  R.skip.name: "Skip",
  R.itemsInfo.name: "Items info",
  R.passItem.name: "Pass item",
  R.profile.name: "Profile",
  R.location.name: "Location",
  R.regions.name: "Regions",
  R.selected.name: "Selected",
  R.selectLocation.name: "Select a map location",
  R.openingNewStore.name: "Opening new store...",
  R.selectRegions.name: "Select regions",
  R.selectCategories.name: "Select categories",
  R.searchHere.name: "Search Here",
  R.apply.name: "Apply",
  R.numOrders.name: "Number of orders",
  R.soo9Choice.name: " Sou9 Choice",
  R.sortedBy.name: "Sorted by",
  R.numLikes.name: "Number of Likes",
  R.sort.name: "Sort",
  R.addMapLocation.name: "Add map location",
  R.country.name: "Country",
  R.geoLocation.name: "Geo Location",
  R.select.name: "Select",
  R.aMomentAgo.name: "A moment ago",
  R.error.name: "Error",
  R.other.name: "Other",
  R.messages.name: "Messages",
  R.letsSwap.name: "LetsSwap",
  R.order.name: "Order",
  R.received.name: "Received",
  R.pending.name: "Pending",
  R.clientOrders.name: "Client orders",
  R.frequentlyAskedQuestions.name: "Frequently asked questions",
  R.sellerOrders.name: "Seller orders",
  R.titleInfo.name: "This will the main name that will appear on the search",
  R.noOrders.name: " You don't have orders",
  R.orders.name: "Orders",
  R.recieved.name: "Recieved",
  R.reminder.name: "Reminder",
  R.refund.name: "Refund",
  R.addStore.name: "Add store",
  R.addFavorite.name: "Add Favorite",
  R.ownedItem.name: "You can not order an item that you own",
  R.ok.name: "OK",
  R.avgReview.name: "Average review",
  R.review.name: "Review",
  R.acceptRefund.name: "Accept refund",
  R.declineRefund.name: "Decline refund",
  R.client.name: "Client",
  R.seller.name: "Seller",
  R.sendPackage.name: "Send package",
  R.deliveryInfo.name: "Delivery info",
  R.loggingOut.name: "Logging out...",
  R.createNewStore.name: "Create new store",
  R.fillCurrency.name: "Fill currency",
  R.checkOrder.name: "Check order",
  R.info.name: "Info",
  R.stats.name: "Stats",
  R.additionalInfo.name: "Additional Info",
  R.contactClientService.name: "Client service",
  R.orderID.name: "Order ID:",
  R.checkAddress.name:
      "The delivery address info are incomplete. Please update your information before submitting the order.",
  R.count.name: "Count",
  R.hideItem.name: "Hide the item",
  R.restoreItem.name: "Restore the item",
  R.pleaseLogIn.name: "Please log in/ sign in",
  R.logIn.name: "Log in",
  R.updateInfo.name: "Update info",
  R.description.name: "Description",
  R.uploadItem.name: "Upload item",
  R.existAlready.name: "Exist already",
  R.empty.name: "Empty",
  R.add.name: "Add",
  R.fillPrice.name: "Fill price",
  R.likes.name: "Likes",
  R.swaps.name: "Swaps",
  R.accept.name: "Accept",
  R.failed.name: "Failed",
  R.currency.name: "Currency",
  R.newItem.name: "New item",
  R.markAsSwapped.name: "Mark as swapped",
  R.decline.name: "Decline",
  R.viewAll.name: "View all >",
  R.fAQ.name: "F.A.Q.",
  R.homePage.name: "Home",
  R.allItems.name: "All items",
  R.pleaseFillName.name: "Please fill your name first",
  R.addKeyword.name: "Please add at least one keyword",
  R.name.name: "Name",
  R.continu.name: "Continue",
  R.addImages.name: "Add images",
  R.addLogo.name: "Add logo image",
  R.addBackgroundImage.name: "Add background image",
  R.sixImagesMax.name: "6 images max",
  R.itemInfo.name: "These are the items you have added to your swap list",
  R.uploadingItem.name: "Uploading item...",
  R.alreadySubmitting.name: "Already submitting",
  R.failedLoadingItem.name: " Failed loading item",
  R.addOneImage.name: "Add at least one image",
  R.pleaseAddLogo.name: "Please add a logo image",
  R.pleaseAddBackground.name: "Please add background image",
  R.createNewItem.name: "Create new item",
  R.email.name: "Email",
  R.link.name: "Link",
  R.otherInfo.name: "Other info",
  R.source.name: "Source",
  R.filters.name: "Filters",
  R.category.name: "Category",
  R.categories.name: "Categories",
  R.moments.name: "Moments",
  R.contact.name: "Contact",
  R.reviews.name: "Reviews",
  R.saleServices.name: "Sale services",
  R.paymentOptions.name: "Payment options",
  R.addSubCategory.name: "Add sub-category",
  R.addNote.name: "Add note",
  R.submittingOrder.name: "Submitting order",
  R.success.name: "Success",
  R.selectOption.name: "Select option",
  R.becomeSeller.name: "How to become a seller",
  R.save.name: "Save",
  R.openNewStore.name: "Open a new store",
  R.sendingReminder.name: "Sending reminder...",
  R.applyingRefund.name: "Applying for refund...",
  R.addingReview.name: "Adding a review...",
  R.openingStore.name: "Opening Store...",
  R.updatingAddress.name: "Updating address...",
  R.loading.name: "Loading...",
  R.checkOutThisItem.name: "checkOutThisItemEN",
  R.bestShopping.name: "Best Shopping Experience",
  R.bestShoppingDescription.name:
      "Find the best online deals for products of Home Appliances, Jewellery, Watches, Food Supplements, Skin Care and much more.",
  R.fastDelivery.name: "Fast Delivery",
  R.fastDeliveryDescription.name:
      "Online shopping became fun just because of our platform. We deliver products all over the country, facilitating the customers.",
  R.cod.name: "Secure Payment",
  R.codDescription.name:
      "We offer the easiest payment methods like cash on delivery, credit card and credit card on delivery.",
  R.greatCustomerService.name: "Great Customer Service",
  R.awesomeAfterSales.name: "Awesome after sales",
  R.excellentProducts.name: "Excellent line up of products",
  R.competitivePrices.name: "Competitive Prices",
  R.haveItAll.name: "We have it all!!!",
  R.tenImagesMax.name: "10 images max",
  R.pleaseAddTitle.name: "Please add a catchy title to engage customers",
  R.pleaseAddDescription.name: "Please add a description for your item.",
  R.pleaseAddAdditionalInfo.name:
      "You can add additional information about your item. (return policy, delivery terms, warranty... ect.",
  R.pleaseAddCategory.name: "Please choose the category to which your item belongs.",
  R.pleaseAddTags.name:
      "Please add search tags. (Example for a power bank: power bank, battery, charger, ... ect.).",
  R.itemPhotos.name: "Item's photos",
  R.pleaseAddItemPhotos.name:
      "Please upload photos of your item. (These images will be displayed on top).",
  R.additionalItemPhotos.name: "Additional photos",
  R.pleaseAddAdditionalItemPhotos.name:
      "Please upload additional descriptive images. (Example: User manual, warranties, promotion ect.).",
  R.options.name: "Options",
  R.pleaseAddOption.name: "Please add customizations options. (Example: Color, Size, weight...).",
  R.pleaseAddPrice.name:
      "Please add the base price of your product. (If you have specific prices for different item options you can add in the customization options).",
  R.pleaseAddComparePrice.name:
      "You can add a compare price useful to show the old price for example.",
  R.supplierInfo.name: "Supplier info",
  R.pleaseAddSupplierInfo.name:
      "You can add information about your supplier here. This information will not be shared with customers (only you can see it).",
  R.subOptions.name: "Sub-options",
  R.pleaseAddSubOptions.name: "Please add available sub-options. (Example: Red, Blue, Green...).",
  R.updatingItem.name: "Updating item...",
  R.callDetails.name: "Details",
  R.callID.name: "ID",
  R.noCalls.name: "No calls",
  R.newOrder.name: "New order",
  R.remindSeller.name: "Seller reminded",
  R.orderReceived.name: "Order received",
  R.refundApplication.name: "Refund application",
  R.itemPackaged.name: "Item packaged",
  R.packageSent.name: "Package sent",
  R.confirmOrder.name: "Order confirmed",
  R.addReview.name: "Review added",
  R.uploadingPost.name: "Uploading Post",
  R.updatingPost.name: "Updating Post",
  R.hidePost.name: "Hide post",
  R.restorePost.name: "Restore post",
  R.subSubProvince.name: "subSubProvince",
  R.tagLocation.name: "tagLocation",
  R.createPost.name: "Create post",
  R.upload.name: "Upload",
  R.comments.name: "Comments",
  R.submittingComment.name: "Submitting comment",
  R.checkOutThisPost.name: "Check out this post",
  R.addComment.name: "Add Comment",
  R.cancel.name: "Cancel",
  R.businesses.name: "Businesses",
  R.clients.name: "Clients",
  R.registerBusiness.name: "Register Business",
  R.back.name: "Back",
  R.storeName.name: "Store Name",
  R.firstName.name: "First Name",
  R.lastName.name: "Last Name",
  R.fillStoreInfoDescription.name: "Fill store info description",
  R.fillAuthorInfoDescription.name: "Fill author info description",
  R.fillStoreLocationDescription.name: "Fill store location description",
  R.registration.name: "Registration",
  R.fillLanguageSkills.name: "Fill language skills",
  R.fillIdentityInfo.name: "Fill identity information",
  R.fillWorkRegion.name: "Fill work region",
  R.hourlyRate.name: "Hourly Rate",
  R.addPhoto.name: "Add Photo",
  R.sendJobApplication.name: "Send Job Application",
  R.selectLanguage.name: "Select Language",
  R.english.name: "English",
  R.arabic.name: "Arabic",
  R.french.name: "French",
  R.chinese.name: "Chinese",
  R.next.name: "Next",
  R.discover.name: "Discover",
  R.store.name: "Store",
  R.nearby.name: "Nearby",
  R.follow.name: "Follow",
  R.home.name: "Home",
  R.translators.name: "Translators",
  R.urgency.name: "Urgency",
  R.accountSecurity.name: "Account Security",
  R.privacySettings.name: "Privacy Settings",
  R.notificationSettings.name: "Notification Settings",
  R.generalSettings.name: "General Settings",
  R.fontSize.name: "Font Size",
  R.darkMode.name: "Dark Mode",
  R.helpCenter.name: "Help Center",
  R.appreciation.name: "Appreciation",
  R.links.name: "Links",
  R.workWithUs.name: "Work With Us",
  R.aboutUs.name: "About Us",
  R.personalInformation.name: "Personal information",
  R.history.name: "History",
  R.cart.name: "Cart",
  R.coupons.name: "Coupons",
  R.wishList.name: "Wish List",
  R.vip.name: "VIP",
  R.guidelines.name: "Guidelines",
  R.version.name: "Version",
  R.termsOfUse.name: "Terms of Use",
  R.privacyTerms.name: "Privacy Terms",
  R.addBiography.name: "Add a biography to help people know you",
  R.chooseLocation.name: "Choose a location",
  R.selectGender.name: "Select a gender",
  R.selectBirthDay.name: "Select your birth day",
  R.editBiography.name: "Edit Biography",
  R.gender.name: "Gender",
  R.birthDate.name: "Birth Date",
  R.biography.name: "Biography",
  R.settings.name: "Settings",
  R.help.name: "Help",
  R.scan.name: "Scan",
  R.algeria.name: "Algeria",
  R.morroco.name: "Morroco",
  R.tunisia.name: "Tunisia",
  R.egypt.name: "Egypt",
  R.language.name: "Language",
  R.editName.name: "Edit name",
  R.selectCountry.name: "Select country",
  R.editBirthday.name: "Edit birthday",
  R.female.name: "Female",
  R.male.name: "Male",
  R.scheduledTranslation.name: "Scheduled translation",
  R.currentTranslation.name: "Current translation",
  R.online.name: "Online",
  R.offline.name: "Offline",
  R.to.name: "To",
  R.startDate.name: "Start date",
  R.time.name: "Time",
  R.endDate.name: "End date",
  R.selectDate.name: "Select date",
  R.by.name: "By",
  R.selectMethod.name: "Select method",
  R.translatorClass.name: "Translator class",
  R.searchTranslator.name: "Search translator",
  R.phone.name: "Phone",
  R.number.name: "Number",
  R.becomeExpert.name: "Become a Fibali EXPERT",
  R.downloadExpertApp.name: "Please download the our EXPERT APP",
  R.topTranslators.name: "Top translators",
  R.languages.name: "Languages",
  R.findTranslator.name: "Find your translator",
  R.bestTranslatorsCatalog.name: "Best translators catalog",
  R.myPreviousTranslationSessions.name: "My previous translation sessions",
  R.translationDetails.name: "Translation details",
  R.shopping.name: "Shopping",
  R.china.name: "China",
  R.personal.name: "Personal",
  R.business.name: "Business",
  R.hotels.name: "Hotels",
  R.rental.name: "Rental",
  R.flights.name: "Flights",
  R.experts.name: "Experts",
  R.doctors.name: "Doctors",
  R.gabi.name: "Gabi",
  R.food.name: "food",
  R.swap.name: "Swap",
  R.workUnderProgress.name: "Work under progress",
  R.comingSoon.name: "Coming soon",
  R.supplier.name: "Supplier",
  R.supplierSupplierDescription.name: "Supplier supplier description",
  R.onlineShop.name: "Online shop",
  R.onlineShopBusinessDescription.name: "Online shop business description",
  R.housing.name: "Housing",
  R.housingBusinessDescription.name: "Housing business description",
  R.xiaoYi.name: "Xiaoyi",
  R.xiaoYiBusinessDescription.name: "Xiaoyi business description",
  R.carRental.name: "Car rental",
  R.carRentalBusinessDescription.name: "Car rental business description",
  R.foodDelivery.name: "Food delivery",
  R.foodDeliveryBusinessDescription.name: "Food delivery business description",
  R.medical.name: "Medical",
  R.medicalBusinessDescription.name: "Medical business description",
  R.connectClient.name: "Connect with client",
  R.call.name: "Call",
  R.pleaseAddBio.name: "Please add bio",
  R.addLanguage.name: "Add language",
  R.acceptOnlineTranslation.name: "Accept online translation",
  R.acceptOfflineTranslation.name: "Accept offline translation",
  R.addMinTwoTranslationLanguages.name: "Add at least two translation languages",
  R.addTranslatorBiography.name: "Add translator biography",
  R.hourlyRateHint.name: "Add Hourly rate",
  R.firstNameHint.name: "Add First name",
  R.lastNameHint.name: "Add Last name",
  R.storeNameHint.name: "Add Store name",
  R.descriptionHint.name: "Add Description",
  R.keywordsHint.name: "Add Keywords",
  R.nameHint.name: "Add Name",
  R.streetAddressHint.name: "Add Street address",
  R.titleHint.name: "Add Title",
  R.priceHint.name: "Add Price",
  R.comparePriceHint.name: "Add Compare price",
  R.emailHint.name: "Add Email",
  R.linkHint.name: "Add Link",
  R.otherInfoHint.name: "Add Other info",
  R.optionsHint.name: "Add Options",
  R.countHint.name: "Add Count",
  R.deliveryInfoHint.name: "Add Delivery info",
  R.communicationMethod.name: "Communication method",
  R.languageSkills.name: "Language skills",
  R.identityInfo.name: "Identity info",
  R.photo.name: "Photo",
  R.addProfilePhoto.name: "Add profile photo",
  R.userProfileTempBlocked.name: "User profile can't be accessed at the moment",
  R.someDayWriteBio.name: "Some day write bio",
  R.unfollow.name: "Unfollow",
  R.sendSms.name: "Send code",
  R.missingPhoneNumber.name: "Missing phone number",
  R.pleaseAddPhoneNumber.name: "Please add phone number",
  R.pleaseAddProfilePhoto.name: "Please add profile photo",
  R.media.name: "Media",
  R.biographyHint.name: "Add Biography",
  R.countryHint.name: "Add Country",
  R.categoryHint.name: "Add Category",
  R.addTags.name: "Add tags",
  R.tagsHint.name: "Add Tags",
  R.tag.name: "Tag",
  R.reject.name: "Reject",
  R.cameraPermissionDenied.name: "Camera permission denied",
  R.pleaseGrantCameraPermission.name: "Please grant camera permission",
  R.microphonePermissionDenied.name: "Microphone permission denied",
  R.pleaseGrantMicrophonePermission.name: "Please grant microphone permission",
  R.needCameraMicrophonePermission.name: "Need camera and microphone permission",
  R.pleaseGrantCameraMicrophonePermission.name: "please grant camera and microphone permission",
  R.grantPermission.name: "Grant permission",
  R.callLogs.name: "Call logs",
  R.details.name: "Details",
  R.translations.name: "Translations",
  R.rating.name: "Rating",
  R.message.name: "Message",
  R.video.name: "Video",
  R.editImages.name: "Edit images",
  R.longPressChangeOrder.name: "Long press on the image to change order",
  R.numberLimited.name: "Number limited",
  R.ifLeaveChangesDiscarded.name: "Changes not saved will be discarded",
  R.discard.name: "Discard",
  R.kReturn.name: "Return",
  R.findingTranslatorEasy.name: "Finding translator easy",
  R.connect.name: "Connect",
  R.appointmentNotAvailable.name: "Appointment not available",
  R.register.name: "Register",
  R.translatorApplicationUnderReview.name: "Translator application under review",
  R.translatorFired.name: "Translator fired",
  R.translatorSuspended.name: "Translator suspended",
  R.contactUs.name: "Contact us",
  R.appeal.name: "Appeal",
  R.kClass.name: "Class",
  R.flash.name: "Flash",
  R.type.name: "Type",
  R.selectLanguages.name: "Select languages",
  R.complete.name: "Complete",
  R.canceled.name: "Canceled",
  R.lookingForTranslator.name: "Looking for translator",
  R.connectWithClient.name: "Connect with client",
  R.currentSession.name: "Current session",
  R.translationRequests.name: "Translation requests",
  R.pleaseCompleteCurrentSession.name: "Please complete current session",
  R.confirm.name: "Confirm",
  R.enable.name: "Enable",
  R.inApp.name: "InApp",
  R.duration.name: "Duration",
  R.addCall.name: "Add call",
  R.reportIssue.name: "Report issue",
  R.like.name: "Like",
  R.pass.name: "Pass",
  R.congratulation.name: "Congratulation",
  R.chooseSource.name: "Choose source",
  R.pleaseAddCurrency.name: "Please add currency",
  R.currencyHint.name: "Add Currency",
  R.address.name: "Address",
  R.addressHint.name: "Add Address",
  R.subscriptions.name: "Subscriptions",
  R.myProducts.name: "My products",
  R.storeInfo.name: "Store info",
  R.additionalInfoHint.name: "Add Additional info",
  R.salePrice.name: "Sale price",
  R.salePriceHint.name: "Add Sale price",
  R.pleaseAddSalePrice.name: "Please add sale price",
  R.storeItems.name: "Store items",
  R.addDescription.name: "Add description",
  R.selectCurrency.name: "Select currency",
  R.editStore.name: "Edit store",
  R.editProfilePhoto.name: "Edit profile photo",
  R.oldItemsInterrogationDescription.name: "Old items interrogation description",
  R.oldItemsPiling.name: "Old items piling",
  R.swapThem.name: "Swap them",
  R.shareThemTitle.name: "Share them title",
  R.shareThemDescription.name: "Share them description",
  R.oldItemsPilingTitle.name: "Old items piling title",
  R.oldItemsPilingDescription.name: "Old items piling description",
  R.findBestItemsAroundTitle.name: "Find best items around title",
  R.findBestItemsAroundDescription.name: "Find best items around description",
  R.matchChatExchangeTitle.name: "Exchanging was never this easy",
  R.matchChatExchangeDescription.name:
      "Upload the item you want to exchange, find a match, chat, make a deal and exchange it now!",
  R.detail.name: "Detail",
  R.date.name: "Date",
  R.general.name: "General",
  R.support.name: "Support",
  R.inviteFriend.name: "Invite friend",
  R.account.name: "Account",
  R.yourProfile.name: "Your profile",
  R.settingsBelow.name: "Below are your settings",
  R.active.name: "Active",
  R.inactive.name: "Inactive",
  R.matches.name: "Matches",
  R.matchesInfo.name: "Matches info",
  R.instantMatch.name: "Instant match",
  R.instantMatchInfo.name:
      "When you have an item that someone else liked, his/her items will appear here. Once you like back one of the there items, you will be instantly matched and you can start chatting",
  R.mySwaps.name: "My swaps",
  R.item.name: "Item",
  R.declined.name: "Declined",
  R.hideSwap.name: "Hide swap",
  R.restoreSwap.name: "Restore swap",
  R.uploadingSwap.name: "Uploading swap",
  R.updatingSwap.name: "Updating swap",
  R.locationDenied.name: "GPS location denied",
  R.enableLocation.name: "Enable location",
  R.pleaseEnableLocation.name: "Please enable GPS location",
  R.locationDeniedPermanently.name: "GPS location denied permanently",
  R.locationDisabled.name: "GPS location disabled",
  R.privacy.name: "Privacy",
  R.update.name: "Update",
  R.shareAppTitle.name: "Share app title",
  R.shareAppDescription.name: "Share app description",
  R.chatNotFound.name: "Chat not found",
  R.addReply.name: "Add reply",
  R.moreReplies.name: "More replies",
  R.reply.name: "Reply",
  R.views.name: "Views",
  R.blockedBy.name: "Blocked by",
  R.blocked.name: "Blocked",
  R.unblock.name: "Unblock",
  R.acceptFriend.name: "Accept friend",
  R.cancelFriendRequest.name: "Cancel friend request",
  R.friends.name: "Friends",
  R.requestFriend.name: "Request friend",
  R.declineFriendRequest.name: "Decline friend request",
  R.sendFriendRequest.name: "Send friend request",
  R.searchSettings.name: "Search settings",
  R.addLocation.name: "Add location",
  R.proposeSwap.name: "Propose swap",
  R.newMatch.name: "New match",
  R.foundNewMatch.name: "You have found a match!!!",
  R.addCategory.name: "Add category",
  R.contacts.name: "Contacts",
  R.following.name: "Following",
  R.followers.name: "Followers",
  R.requests.name: "Requests",
  R.invitations.name: "Invitations",
  R.blockedByUserDescription.name: "Blocked by user description",
  R.followBack.name: "Follow back",
  R.accepted.name: "Accepted",
  R.shoppingNotAvailableInThisCountry.name: "Shopping not available in this country",
  R.km.name: "KM",
  R.searchSwapsAroundTitle.name: "The easiest and most convenient way to exchange your items",
  R.searchSwapsAroundDescription.name:
      "No More Wasting Time and Money on Unnecessary Purchases. Fibali is a leading exchange network that offres a free, fun, and interactive way to exchange items with others in the your community",
  R.numOfItems.name: "Number of items",
  R.changeLocation.name: "Select location",
  R.addFirstSwapItemTitle.name: "Share Your First Item",
  R.addFirstSwapItemDescription.name:
      "Become part of Fibali's leading swap network by sharing your first item, upload your first item now!",
  R.checkOutThisSwapItem.name: "Join Fibali's leading swapping network, and start exchanging now!",
  R.noSwaps.name: "No swaps to be found here",
  R.commentInfoHint.name: "Add comment",
  R.commentInfo.name: "Comment",
  R.seeMore.name: "See more",
  R.booking.name: "Booking",
  R.tooltipSwapLocationButtonDescription.name: "You can change the item's search region from here.",
  R.tooltipSwapSettingsButtonDescription.name:
      "Select the proper distance for your search from here.",
  R.tooltipSwapBoardButtonDescription.name:
      "You can upload, manage, and check your items from here.",
  R.tooltipSwapChatsButtonDescription.name:
      "Chat with other users for and exchange your items from here.",
  R.tooltipSwapRewindButtonDescription.name: "Reset all previously skipped items from here.",
  R.swapDeclined.name: "Swap Declined",
  R.swapAccepted.name: "Swap Accepted",
  R.swapCanceled.name: "Swap Canceled",
  R.addSwapReview.name: "Add Review",
  R.relation.name: "Relation",
  R.post.name: "Post",
  R.orderEvent.name: "Order Event",
  R.translatorCall.name: "Translator Call",
  R.newPostComment.name: "New Comment",
  R.newPostLike.name: "New like",
  R.newPost.name: "New post",
  R.newCommentReply.name: "New reply",
  R.friendRequest.name: "Friend request",
  R.friendRequestAccepted.name: "Friend request accepted",
  R.newFollow.name: "New follow",
  R.newSwapItemReview.name: "New Swap Review",
  R.newSwapItemLike.name: "New like",
  R.addFirstPost.name: "New in Fibali! Share what you have in mind with others.",
  R.privacyNSecurity.name: "Privacy & Security",
  R.deleteAccount.name: "Delete account",
  R.gallery.name: "Gallery",
  R.emptyNotificationsTitle.name: "Empty Notifications",
  R.emptyNotificationsDescription.name: "No notifications to be found",
  R.liked.name: "Liked",
  R.report.name: "Report",
  R.lightMode.name: "Light Mode",
  R.brightness.name: "Brightness",
  R.termsOfService.name: "Terms of Service",
  R.skipLogging.name: "Skip Logging",
  R.termsAndConditions.name: "Terms and Conditions",
  R.iAgreeToTheTermsAndConditions.name: "I Agree to the Terms and Conditions",
  R.viewTermsAndConditions.name: "View Terms and Conditions",
  R.loggingIn.name: "Logging In",
  R.askAgreeTermsConditions.name:
      "Hi, there!\\n\\nWelcome to Fibali, the new app that connects you with people who want to swap items they no longer need.\\n\\nBefore you start swapping, we need you to agree to our terms and conditions. These are a set of rules that outline your rights and obligations as a user of our app. They also address important issues such as intellectual property rights, dispute management, and acceptable conduct.\\n\\nBy agreeing to our terms and conditions, you confirm that you have read, understand, and agree to be bound by them. You also agree to comply with our acceptable use policy, which is incorporated by reference into our terms and conditions.\\n\\nOur terms and conditions are a legally binding contract between you and us, so please read them carefully. If you have any questions or concerns, please contact us at piicubic@gmail.com. We are happy to help.\\n\\nTo view our terms and conditions, please click on the link below. To accept them and continue using our app, please check the box and click on the button below.",
  R.place.name: "Place",
  R.block.name: "Block",
  R.blockUserDescription.name:
      "Are you sure you want to block this user? Blocking will permanently prevent them from contacting you or viewing your profile. However, you can unblock them later if you change your mind.",
  R.blockedUsers.name: "Blocked Users",
  R.noBlockedUsers.name: "No Blocked Users",
  R.oopsSomethingWentWrong.name: "Oops! Something went wrong.",
  R.unBlockUserDescription.name:
      "Are you sure you want to unblock this user? Once unblocked, they will be able to contact you and view your profile again.",
  R.userNotFound.name: "User Not Found",
  R.blockedAt.name: "Blocked At",
  R.youHaveBeenBlockedByThisUser.name: "You have been blocked by this user.",
  R.youHaveBlockedThisUser.name: "You have blocked this user.",
  R.storeNotFound.name: "Store Not Found",
  R.storeNotAvailable.name: "Store Not Available",
  R.about.name: "About",
  R.noPostHere.name: "No posts here",
  R.whyNotShare.name: "Why not share what's on your mind and see what others have to say?",
  R.followOtherUsersAndGetUpdated.name:
      "Follow other users and get updated on their latest posts here",
  R.likedPostsWillAppearHere.name: "Liked posts will appear here",
  R.commentedPostsWillAppearHere.name: "Commented posts will appear here",
  R.swapIntroDescription.name:
      "Find and swap the items you don’t need for the ones you want with a simple tap",
  R.connectIntroDescription.name: "Swap items and ideas, share your thoughts and meet new people",
  R.fashion.name: "fashion",
  R.beauty.name: "beauty",
  R.travel.name: "travel",
  R.family.name: "family",
  R.health.name: "health",
  R.fitness.name: "fitness",
  R.music.name: "music",
  R.movies.name: "movies",
  R.specialEvents.name: "special events",
  R.hobbies.name: "hobbies",
  R.technology.name: "technology",
  R.homeDecor.name: "home decor",
  R.dIY.name: "DIY",
  R.gardening.name: "gardening",
  R.finance.name: "finance",
  R.studentLife.name: "student life",
  R.pets.name: "pets",
  R.currentNews.name: "current news",
  R.science.name: "science",
  R.newUpdateAvailableTitle.name: "New update available",
  R.newUpdateAvailableDescription.name:
      "We have a new version available for you to download. Please update to the latest version to enjoy the latest features and improvements.",
  R.notification.name: "notification",
  R.swipeRightDescription.name:
      "Swiping an item right means you like it. If it's owner user likes your items back, you will be matched for exchange.",
  R.swipeLeftDescription.name:
      "Swiping an item left means you are not interested in it. You will not see this item again.",
  R.noChatsYetTitle.name: "No chats yet",
  R.noChatsYetDescription.name: "Add new friends and start conversations",
  R.whoCanMyPost.name: "Who can see my post?",
  R.comment.name: "Comment",
  R.needToLogin.name: "You need to login to continue",
  R.finishSwipingToSeeMore.name: "Finish swipping all items to see more",
  R.pleaseAllowAccessToGPSLocation.name:
      "Fibali needs access to your GPS location to find nearby items",
  R.addPrice.name: "Add Price",
  R.deleteItemWarning.name: "Are you sure you want to delete this item?",
  R.cantReachNetwork.name: "Can't reach network",
  R.pleaseCheckYourNetworkNTryAgain.name: "Please check your network and try again",
  R.noInternetConnection.name: "No internet connection",
  R.viewedPostsWillAppearHere.name: "Viewed posts will appear here",
  R.swapsWillAppearHere.name: "Swaps will appear here",
  R.noComments.name: "No comments",
  R.readMore.name: "Read more",
  R.showLess.name: "Show less",
  R.startingLiveVideo.name: "Starting live video...",
  R.liveVideoStarted.name: "Live video started",
  R.liveIsAlreadyStarting.name: "Live is already starting ...",
  R.startLiveStreaming.name: "Start LIVE streaming",
  R.myStores.name: "My stores",
  R.stores.name: "Stores",
  R.catalog.name: "Catalog",
  R.postNotFound.name: "Post not found",
  R.cantOpen.name: "Can't open",
  R.remove.name: "Remove",
  R.sevenDayReturnPolicy.name: "7 day return policy",
  R.fourteenDayReturnPolicy.name: "14 day return policy",
  R.thirtyDayReturnPolicy.name: "30 day return policy",
  R.sixtyDayReturnPolicy.name: "60 day return policy",
  R.ninetyDayReturnPolicy.name: "90 day return policy",
  R.noReturnPolicy.name: "No return policy",
  R.sevenDayReturnPolicySellerDescription.name:
      "This policy is ideal for items that are quickly consumable or have a short shelf-life. It provides your customers with a full week to return the product if it doesn\'t meet their expectations.",
  R.fourteenDayReturnPolicySellerDescription.name:
      "This policy is great for fast-moving consumer goods. It provides you with two weeks to return a product if it doesn\'t meet your expectations.",
  R.thirtyDayReturnPolicySellerDescription.name:
      "This is the most common return policy. It gives you a full month to decide if you want to keep a product.",
  R.sixtyDayReturnPolicySellerDescription.name:
      "This policy is less common but can be used for higher-value items that you might need more time to evaluate.",
  R.ninetyDayReturnPolicySellerDescription.name:
      "This is a generous return policy often used by businesses that are very confident in their products. It can be a strong selling point for customers.",
  R.noReturnPolicySellerDescription.name:
      "This item is final sale and not eligible for return. This policy is ideal for items that cannot be resold due to health or hygiene reasons, custom-made items, or clearance items.",
  R.sevenDayReturnPolicyBuyerDescription.name:
      "You have 7 days to return this item for a full refund.",
  R.fourteenDayReturnPolicyBuyerDescription.name:
      "You have 14 days to return this item for a full refund.",
  R.thirtyDayReturnPolicyBuyerDescription.name:
      "You have 30 days to return this item for a full refund.",
  R.sixtyDayReturnPolicyBuyerDescription.name:
      "You have 60 days to return this item for a full refund.",
  R.ninetyDayReturnPolicyBuyerDescription.name:
      "You have 90 days to return this item for a full refund.",
  R.noReturnPolicyBuyerDescription.name: "This item is not eligible for return.",
  R.defectiveOrDamaged.name: "Defective or damaged",
  R.defectiveOrDamagedSellerDescription.name:
      "This condition allows for returns of items that arrived defective or have developed a defect within a reasonable period of use. It covers manufacturing defects, shipping damage, or malfunctions that occur under normal use. This protects buyers from being stuck with faulty products.",
  R.defectiveOrDamagedBuyerDescription.name:
      "You can return this item if it is defective or damaged. This includes items that arrived with defects, developed problems within a reasonable time of use, or were damaged during shipping. Please provide details about the defect or damage when requesting a return.",
  R.notAsDescribed.name: "Not as described",
  R.notAsDescribedSellerDescription.name:
      "This condition permits returns if the item received significantly differs from its description or advertised features. It covers discrepancies in size, color, functionality, or other essential characteristics. This protects buyers from misleading or inaccurate product information.",
  R.notAsDescribedBuyerDescription.name:
      "You can return this item if it is not as described in the listing. This includes items that are different in size, color, features, or other significant aspects compared to the product description. Please provide details about the discrepancies when requesting a return.",
  R.unusedAndInOriginalCondition.name: "Unused and in original condition",
  R.unusedAndInOriginalConditionSellerDescription.name:
      "This is a standard condition that ensures items are returned in the same state they were received. It typically applies to unopened items, products with unbroken seals, or those with no signs of wear or use. This protects sellers from accepting used or damaged items for returns.",
  R.unusedAndInOriginalConditionBuyerDescription.name:
      "The item must be returned in its original condition and packaging. It should be unopened, unused, and with all original tags and labels intact. Please ensure the item is carefully packaged to avoid damage during return shipping.",
  R.inStoreReturns.name: 'Drop-off at a physical location',
  R.inStoreReturnsSellerDescription.name:
      'Allow customers to drop off their return package at a physical location. Drop-off locations can be your store, a warehouse, or a third-party location.',
  R.mailReturns.name: 'Mail returns',
  R.mailReturnsSellerDescription.name: 'Allow customers to mail their return package to you.',
  R.homeOfficePickup.name: 'Home or office pickup returns',
  R.homeOfficePickupSellerDescription.name:
      'Arrange for a courier to collect the return package directly from the customer\'s address.',
  R.inStoreExchanges.name: "In store exchanges",
  R.inStoreExchangesSellerDescription.name:
      "Allow customers to exchange their item for another one in your store.",
  R.mailExchanges.name: "Mail exchanges",
  R.mailExchangesSellerDescription.name:
      "Allow customers to mail their item to you for an exchange.",
  R.homeOfficeExchanges.name: "Home or office pickup exchanges",
  R.homeOfficeExchangesSellerDescription.name:
      "Arrange for a courier to collect the item directly from the customer's address for an exchange.",
  R.shared.name: "Shared",
  R.returnPolicy.name: 'Return policy',
  R.returnPolicyDescription.name:
      'A return policy tells customers how many days they have to return an item and get a refund.',
  R.chooseReturnTimeFrame.name: 'Choose a return policy',
  R.acceptExchange.name: 'Accept exchanges',
  R.acceptExchangeDescription.name:
      'Specify how customers can exchange items. You can choose one or more options.',
  R.returnOptions.name: 'Return options',
  R.returnOptionsDescription.name:
      'Specify how customers can return items. You can choose one or more options.',
  R.sellerPaysForExchangeShippingFee.name:
      'The seller pays for the exchange shipping fee. The exchanges are free of charge for the clients.',
  R.clientPaysForExchangeShippingFee.name:
      'The client pays for the exchange shipping fee. The seller bears the cost of the exchange shipping fee.',
  R.sharedPaymentForExchangeShippingFee.name:
      'of the exchange shipping fee is payed by the client. The seller bears the remaining cost of the exchange shipping fee.',
  R.conditions.name: 'Conditions',
  R.conditionsDescription.name:
      'Specify the conditions that the item must meet to be eligible for a return.',
  R.noMoreProducts.name: 'No more products',
  R.global.name: 'Global',
};
