import 'package:fibali/fibali_core/utils/strings.dart';

final appLocFR = {
  R.items.name: "Produits",
  R.messageSent.name: "Message envoyé",
  R.keywords.name: "Tags",
  R.phoneNumber.name: "Numéro de téléphone",
  R.province.name: "Wilaya",
  R.subProvince.name: "Commune",
  R.updatingStoreInfo.name: "Mise à jour le magasin",
  R.sellerReminderSent.name: "Le vendeur recevra un rappel pour envoyer la commande",
  R.invalidPhoneNumber.name: "Numéro de téléphone invalide",
  R.locationUnknown.name: "Lieu inconnu",
  R.creatingUser.name: "Création d'un utilisateur",
  R.quote.name: "Commandes",
  R.unknown.name: "Inconnue",
  R.share.name: "Partager",
  R.editProfile.name: "Editer le profil",
  R.addItem.name: "Ajouter un prduit",
  R.updateStoreInfo.name: "Mettre à jour les informations du magasin",
  R.logout.name: "Se déconnecter",
  R.contactInfo.name: "Contact",
  R.from.name: "par",
  R.all.name: "Tout",
  R.send.name: "Envoyer",
  R.mayBeLater.name: "Peut-être plus tard",
  R.quantity.name: "Quantité",
  R.kickOf.name: "KickOf",
  R.search.name: "Chercher",
  R.magazin.name: "Magazine",
  R.price.name: "Prix",
  R.comparePrice.name: "Comparer le prix",
  R.fillDescription.name: "Veuillez remplir une description du produit",
  R.fillTitle.name: "Veuillez remplir le titre du produit",
  R.sellerBoard.name: "Mes magazins",
  R.variants.name: "Options",
  R.addValue.name: "Ajoutez au moins un attribut",
  R.nineMax.name: "Maximum de 9 attributs",
  R.editItem.name: "Modifier le produit",
  R.orderDetails.name: "Détails de la commande",
  R.posts.name: "Des postes",
  R.camera.name: "Caméra",
  R.submit.name: "Soumettre",
  R.alreadyReviewd.name: "Déjà commenté!",
  R.saveNDefault.name: "Enregistrer et définir par défaut",
  R.missingAddress.name: "Adresse de livraison manquante",
  R.pleaseUpdateAddress.name: "Veuillez mettre à jour l'adresse",
  R.total.name: "Le total:",
  R.onlyAlgeria.name: "Seule l'Algérie est disponible pour l'instant!",
  R.checkPhone.name: "Vérifier le téléphone",
  R.getSms.name: "Recevoir des SMS",
  R.streaming.name:
      "Lorsqu'un utilisateur aime l'un de vos produits, ses produits seront visible ici.",
  R.fillOTP.name: "Remplir SMS code",
  R.streetAddress.name: "Adresse de la rue",
  R.addStreetAddress.name: "Ajouter une adresse",
  R.addDeliveryAddress.name: "Ajouter une adresse de livraison",
  R.editDeliveryAddress.name: "Modifier l'adresse de livraison",
  R.addPhoneNumber.name: "Ajouter un numéro de téléphone",
  R.updateAddress.name: "Mettre à jour l'adresse",
  R.deliveryAddress.name: "Adresse de Livraison",
  R.title.name: "Titre",
  R.sixDigitsOTP.name: "Veuillez saisir le code à 6 chiffres du SMS",
  R.code.name: "Code",
  R.checkCode.name: "Vérifier le code",
  R.setting.name: "Réglage",
  R.distance.name: "Distance",
  R.news.name: "Nouvelles",
  R.strictSearchMode.name: "Mode de recherche strict",
  R.oops.name: "Quelque chose s'est mal passé. Veuillez vérifier votre internet et réessayer.",
  R.likeItem.name: "Aimé le produit",
  R.noItems.name:
      "Aucun produit ne correspond à votre recherche \\n Modifier la recherche ou utilisez moins de filtres.",
  R.shareWithFriends.name: "Partagez l'application avec vos amis.",
  R.reload.name: "Recharger",
  R.giveAway.name: "Donner",
  R.edit.name: "Éditer",
  R.notifications.name: "Notifications",
  R.delete.name: "Supprimer",
  R.chat.name: "Chat",
  R.match.name: "Correspondre",
  R.done.name: "Terminé",
  R.skip.name: "Passer",
  R.itemsInfo.name: "Ce sont les articles que vous avez ajoutés à votre liste d'échange",
  R.passItem.name: "Passer le produit",
  R.profile.name: "Compte",
  R.location.name: "Lieu",
  R.regions.name: "Régions",
  R.selected.name: "Choisi",
  R.selectLocation.name: "Sélectionnez un emplacement sur la carte",
  R.openingNewStore.name: "Ouverture d'un nouveau magasin...",
  R.selectRegions.name: "Sélectionnez les régions",
  R.selectCategories.name: "Sélectionnez les catégories",
  R.searchHere.name: "Cherche ici",
  R.apply.name: "Appliquer",
  R.numOrders.name: "Nombre de commandes",
  R.soo9Choice.name: "Best of SOO9",
  R.sortedBy.name: "Trié par",
  R.numLikes.name: "Nombre de J'aime",
  R.sort.name: "Trier",
  R.addMapLocation.name: "Ajouter un emplacement sur la carte",
  R.country.name: "Pays",
  R.geoLocation.name: "Emplacement géographique",
  R.select.name: "Sélectionner",
  R.aMomentAgo.name: "Il y a un moment",
  R.error.name: "Erreur",
  R.other.name: "Autre",
  R.messages.name: "messages",
  R.letsSwap.name: "LetsSwap",
  R.order.name: "Commande",
  R.received.name: "Reçu",
  R.pending.name: "En attente",
  R.clientOrders.name: "Commandes clients",
  R.frequentlyAskedQuestions.name: "Questions-Réponse",
  R.sellerOrders.name: "Commandes du vendeur",
  R.titleInfo.name: "Ce sera le nom principal qui apparaîtra sure votre produit",
  R.noOrders.name: " Vous n'avez pas de commandes",
  R.orders.name: "Commandes",
  R.recieved.name: "Reçu",
  R.reminder.name: "Rappel",
  R.refund.name: "Rembourser",
  R.addStore.name: "Ajouter un magasin",
  R.addFavorite.name: "Ajouter à mes favoris",
  R.ownedItem.name: "Vous ne pouvez pas commander un produit que vous possédez",
  R.ok.name: "OK",
  R.avgReview.name: "Evaluation",
  R.review.name: "Commenter",
  R.acceptRefund.name: "Accepter le remboursement",
  R.declineRefund.name: "Refuser le remboursement",
  R.client.name: "Client",
  R.seller.name: "Vendeur",
  R.sendPackage.name: "Envoyer le produit",
  R.deliveryInfo.name: "Informations de livraison",
  R.loggingOut.name: "Déconnecter...",
  R.createNewStore.name: "Créer un nouveau magasin",
  R.fillCurrency.name: "Remplir la monnaie",
  R.checkOrder.name: "Vérifier la commande",
  R.info.name: "Info",
  R.stats.name: "Statistiques",
  R.additionalInfo.name: "Information additionnelle",
  R.contactClientService.name: "Service client",
  R.orderID.name: "Numéro de commande:",
  R.checkAddress.name:
      "Les informations sur l'adresse de livraison sont incomplètes. Veuillez mettre à jour vos informations avant de soumettre la commande.",
  R.count.name: "Nombre",
  R.hideItem.name: "Masquer le produit",
  R.restoreItem.name: "Restaurer le produit",
  R.pleaseLogIn.name: "Veuillez vous connecter/inscrire",
  R.logIn.name: "Se connecter",
  R.updateInfo.name: "Mettre à jour",
  R.description.name: "Description",
  R.uploadItem.name: "Ajouter le produit",
  R.existAlready.name: "Existe déjà",
  R.empty.name: "Vide",
  R.add.name: "Ajouter",
  R.fillPrice.name: "Remplissez le prix",
  R.likes.name: "Aimés",
  R.swaps.name: "Échanges",
  R.accept.name: "Accepter",
  R.failed.name: "Échec",
  R.currency.name: "Monnaie",
  R.newItem.name: "Nouveau produit",
  R.markAsSwapped.name: "Marquer comme échangé",
  R.decline.name: "Refuser",
  R.viewAll.name: "Voir tout >",
  R.fAQ.name: "Q-R",
  R.homePage.name: "Accueil",
  R.allItems.name: "Tous les produits",
  R.pleaseFillName.name: "Veuillez remplir votre nom",
  R.addKeyword.name: "Veuillez ajouter au moins un mot-clé",
  R.name.name: "Nom",
  R.continu.name: "Continuer",
  R.addImages.name: "Ajouter les photo du produit",
  R.addLogo.name: "Ajouter le logo du magasin",
  R.addBackgroundImage.name: "Ajouter une image de fond",
  R.sixImagesMax.name: "6 images max",
  R.itemInfo.name: "Information sur le produit",
  R.uploadingItem.name: "Téléchargement du produit...",
  R.alreadySubmitting.name: "En soumission...",
  R.failedLoadingItem.name: "Échec du chargement du produit",
  R.addOneImage.name: "Ajouter au moins une image",
  R.pleaseAddLogo.name: "Veuillez ajouter une image de logo",
  R.pleaseAddBackground.name: "Veuillez ajouter une image de fond",
  R.createNewItem.name: "Ouvrir un nouvel élément",
  R.email.name: "Email",
  R.link.name: "Lien",
  R.otherInfo.name: "Autre info",
  R.source.name: "Source",
  R.filters.name: "Filtres",
  R.category.name: "Catégorie",
  R.categories.name: "Catégories",
  R.moments.name: "Moments",
  R.contact.name: "Contact",
  R.reviews.name: "Commentaires",
  R.saleServices.name: "Prestations de vente",
  R.paymentOptions.name: "Options de paiement",
  R.addSubCategory.name: "Ajouter une sous-catégorie",
  R.addNote.name: "Ajouter une note",
  R.submittingOrder.name: "Passer la commande",
  R.success.name: "Succès",
  R.selectOption.name: "Sélectionnez l'option",
  R.becomeSeller.name: "Comment devenir vendeur?",
  R.save.name: "Sauvegarder",
  R.openNewStore.name: "Ouvrir un nouveau magasin",
  R.sendingReminder.name: "Envoi du rappel...",
  R.applyingRefund.name: "Demande de remboursement...",
  R.addingReview.name: "Ajout d'un avis...",
  R.openingStore.name: "Ouverture du magasin...",
  R.updatingAddress.name: "Mise à jour de l'adresse...",
  R.loading.name: "Chargement...",
  R.checkOutThisItem.name: "checkOutThisItemFR",
  R.bestShopping.name: "Excellente Experience d'Achat",
  R.bestShoppingDescription.name:
      "Trouvez les meilleures offres en ligne pour les produits d'électroménager, bijoux, montres, compléments alimentaires, skin care et bien plus encore.",
  R.fastDelivery.name: "Livraison Rapide",
  R.fastDeliveryDescription.name:
      "Nous livrons nos produits dans tout le pays, à la demande de nos clients.",
  R.cod.name: "Paiement Securisé",
  R.codDescription.name:
      "Nous offrons les méthodes de paiement les plus simples comme le paiement à la livraison, paiment en ligne et carte de crédit à la livraison.",
  R.greatCustomerService.name: "Excellent service client",
  R.awesomeAfterSales.name: "Assistance après-vente",
  R.excellentProducts.name: "Excellente gamme de produits",
  R.competitivePrices.name: "Prix compétitifs",
  R.haveItAll.name: "Nous avons tout pour vous plaire!!!",
  R.tenImagesMax.name: "10 images max",
  R.pleaseAddTitle.name: "Veuillez ajouter un titre accrocheur pour engager les clients",
  R.pleaseAddDescription.name: "Veuillez ajouter une description pour votre article.",
  R.pleaseAddAdditionalInfo.name:
      "Vous pouvez ajouter uns informations supplémentaires sur votre article. (conditions de retour, conditions de livraison, garanties... ect.",
  R.pleaseAddCategory.name: "Veuillez choisir la catégorie à laquelle appartient votre article.",
  R.pleaseAddTags.name:
      "Veuillez ajouter uns tags de recherche. (Exemple pour une power bank : power bank, batterie, chargeur, ... ect.).",
  R.itemPhotos.name: "Photos du produit",
  R.pleaseAddItemPhotos.name:
      "Veuillez ajouter uns photos de votre produit. (Ces images seront affichées en premier).",
  R.additionalItemPhotos.name: "Photos supplémentaires",
  R.pleaseAddAdditionalItemPhotos.name:
      "Vous pouvez ajouter uns images descriptives supplémentaires. (Exemple : manuel d'utilisation, garanties, promotion, etc.).",
  R.options.name: "Options",
  R.pleaseAddOption.name:
      "Veuillez ajouter uns options de personnalisation. (Exemple : Couleur, Taille, poids...).",
  R.pleaseAddPrice.name:
      "Veuillez ajouter le prix de base de votre produit. (Si vous avez des prix spécifiques pour différentes options d'articles, vous pouvez les ajouter parmi les option).",
  R.pleaseAddComparePrice.name:
      "Vous pouvez ajouter un prix de comparaison utile pour afficher l'ancien prix par exemple.",
  R.supplierInfo.name: "Informations sur le fournisseur",
  R.pleaseAddSupplierInfo.name:
      "Vous pouvez ajouter ici des informations sur votre fournisseur. Ces informations ne seront pas partagées avec les clients (vous seul pouvez les voir).",
  R.subOptions.name: "Sous-options",
  R.pleaseAddSubOptions.name:
      "Veuillez ajouter les sous-options disponibles. (Exemple : Rouge, Bleu, Vert...).",
  R.updatingItem.name: "Mise à jour du produit...",
  R.callDetails.name: "Détails",
  R.callID.name: "ID",
  R.noCalls.name: "Pas d'appels",
  R.newOrder.name: "Nouvelle commande",
  R.remindSeller.name: "Rappelle envoyé",
  R.orderReceived.name: "Colis reçu",
  R.refundApplication.name: "Remboursement",
  R.itemPackaged.name: "Article emballé",
  R.packageSent.name: "Colis envoyé",
  R.confirmOrder.name: "Commande confirmée",
  R.addReview.name: "Avis ajouté",
  R.uploadingPost.name: "Téléchargement de la publication",
  R.updatingPost.name: "Mise à jour du message",
  R.hidePost.name: "Masquer le message",
  R.restorePost.name: "Restaurer la publication",
  R.subSubProvince.name: "sousSousProvince",
  R.tagLocation.name: "tagEmplacement",
  R.createPost.name: "Créer un article",
  R.upload.name: "Télécharger",
  R.comments.name: "commentaires",
  R.submittingComment.name: "Soumettre un commentaire",
  R.checkOutThisPost.name: "Consultez ce poste",
  R.addComment.name: "Ajouter un commentaire",
  R.cancel.name: "Annuler",
  R.businesses.name: "Entreprises",
  R.clients.name: "Clients",
  R.registerBusiness.name: "Enregistrer une entreprise",
  R.back.name: "Retour",
  R.storeName.name: "Nom du magasin",
  R.firstName.name: "Prénom",
  R.lastName.name: "Nom de famille",
  R.fillStoreInfoDescription.name: "Remplir la description des informations sur le magasin",
  R.fillAuthorInfoDescription.name: "Remplir la description des informations sur l'auteur",
  R.fillStoreLocationDescription.name: "Remplir la description de l'emplacement du magasin",
  R.registration.name: "Inscription",
  R.fillLanguageSkills.name: "Remplir les compétences linguistiques",
  R.fillIdentityInfo.name: "Remplir les informations d'identité",
  R.fillWorkRegion.name: "Remplir la zone de travail",
  R.hourlyRate.name: "Taux horaire",
  R.addPhoto.name: "Ajouter une photo",
  R.sendJobApplication.name: "Envoyer une candidature",
  R.selectLanguage.name: "Choisir la langue",
  R.english.name: "Anglais",
  R.arabic.name: "arabe",
  R.french.name: "Français",
  R.chinese.name: "Chinois",
  R.next.name: "Prochain",
  R.discover.name: "Découvrir",
  R.store.name: "Magasin",
  R.nearby.name: "Tout près d'ici",
  R.follow.name: "Abonnement",
  R.home.name: "Maison",
  R.translators.name: "Traducteurs",
  R.urgency.name: "Urgence",
  R.accountSecurity.name: "Sécurité du compte",
  R.privacySettings.name: "Paramètres de confidentialité",
  R.notificationSettings.name: "Paramètres de notification",
  R.generalSettings.name: "réglages généraux",
  R.fontSize.name: "Taille de police",
  R.darkMode.name: "Mode sombre",
  R.helpCenter.name: "Centre d'aide",
  R.appreciation.name: "Appréciation",
  R.links.name: "Liens",
  R.workWithUs.name: "Travailler avec nous",
  R.aboutUs.name: "À propos de nous",
  R.personalInformation.name: "Informations Personnelles",
  R.history.name: "Histoire",
  R.cart.name: "Chariot",
  R.coupons.name: "Coupons",
  R.wishList.name: "Liste de souhaits",
  R.vip.name: "VIP",
  R.guidelines.name: "Des lignes directrices",
  R.version.name: "Version",
  R.termsOfUse.name: "Conditions d'utilisation",
  R.privacyTerms.name: "Confidentialité et modalités",
  R.addBiography.name: "Ajoutez une biographie pour aider les gens à vous connaître",
  R.chooseLocation.name: "Choisissez un emplacement",
  R.selectGender.name: "Sélectionnez un sexe",
  R.selectBirthDay.name: "Sélectionnez votre jour de naissance",
  R.editBiography.name: "Modifier la biographie",
  R.gender.name: "Le genre",
  R.birthDate.name: "Date de naissance",
  R.biography.name: "Biographie",
  R.settings.name: "Réglages",
  R.help.name: "Aide",
  R.scan.name: "Scan",
  R.algeria.name: "Algérie",
  R.morroco.name: "Maroc",
  R.tunisia.name: "Tunisie",
  R.egypt.name: "Egypte",
  R.language.name: "Langue",
  R.editName.name: "Modifier le nom",
  R.selectCountry.name: "Choisissez le pays",
  R.editBirthday.name: "Modifier l'anniversaire",
  R.female.name: "Femelle",
  R.male.name: "Homme",
  R.scheduledTranslation.name: "Traduction programmée",
  R.currentTranslation.name: "Traduction actuelle",
  R.online.name: "En ligne",
  R.offline.name: "Hors ligne",
  R.to.name: "Pour",
  R.startDate.name: "Date de début",
  R.time.name: "Temps",
  R.endDate.name: "Date de fin",
  R.selectDate.name: "Sélectionner une date",
  R.by.name: "Par",
  R.selectMethod.name: "Sélectionnez la méthode",
  R.translatorClass.name: "Classe de traducteur",
  R.searchTranslator.name: "Traducteur de recherche",
  R.phone.name: "Téléphone fixe",
  R.number.name: "Nombre",
  R.becomeExpert.name: "Devenez un EXPERT Fibali",
  R.downloadExpertApp.name: "Veuillez télécharger notre APP EXPERT",
  R.topTranslators.name: "Meilleurs traducteurs",
  R.languages.name: "Langues",
  R.findTranslator.name: "Trouvez votre traducteur",
  R.bestTranslatorsCatalog.name: "Catalogue des meilleurs traducteurs",
  R.myPreviousTranslationSessions.name: "Mes sessions de traduction précédentes",
  R.translationDetails.name: "Détails de la traduction",
  R.shopping.name: "Achats",
  R.china.name: "Chine",
  R.personal.name: "Personnel",
  R.business.name: "Affaires",
  R.hotels.name: "Hôtels",
  R.rental.name: "De location",
  R.flights.name: "Vols",
  R.experts.name: "Experts",
  R.doctors.name: "Médecins",
  R.gabi.name: "Gaby",
  R.food.name: "nourriture",
  R.swap.name: "Échanger",
  R.workUnderProgress.name: "Travaux en cours",
  R.comingSoon.name: "Bientôt disponible",
  R.supplier.name: "Le fournisseur",
  R.supplierSupplierDescription.name: "Description du fournisseur fournisseur",
  R.onlineShop.name: "Magasin en ligne",
  R.onlineShopBusinessDescription.name: "Description de l'activité de la boutique en ligne",
  R.housing.name: "Logement",
  R.housingBusinessDescription.name: "Description de l'entreprise de logement",
  R.xiaoYi.name: "Xiaoyi",
  R.xiaoYiBusinessDescription.name: "Description de l'activité de Xiaoyi",
  R.carRental.name: "Location de voiture",
  R.carRentalBusinessDescription.name: "Description de l'entreprise de location de voitures",
  R.foodDelivery.name: "Livraison de nourriture",
  R.foodDeliveryBusinessDescription.name: "Description de l'entreprise de livraison de nourriture",
  R.medical.name: "Médical",
  R.medicalBusinessDescription.name: "Description de l'activité médicale",
  R.connectClient.name: "Connectez-vous avec le client",
  R.call.name: "Appel",
  R.pleaseAddBio.name: "Veuillez ajouter la bio",
  R.addLanguage.name: "Ajouter une langue",
  R.acceptOnlineTranslation.name: "Accepter la traduction en ligne",
  R.acceptOfflineTranslation.name: "Accepter la traduction hors ligne",
  R.addMinTwoTranslationLanguages.name: "Ajoutez au moins deux langues de traduction",
  R.addTranslatorBiography.name: "Ajouter la biographie du traducteur",
  R.hourlyRateHint.name: "Ajouter un taux horaire",
  R.firstNameHint.name: "Ajouter un prénom",
  R.lastNameHint.name: "Ajouter le nom de famille",
  R.storeNameHint.name: "Ajouter le nom de magasin",
  R.descriptionHint.name: "Ajouter une description",
  R.keywordsHint.name: "Ajouter un mots clés",
  R.nameHint.name: "Ajouter un nom",
  R.streetAddressHint.name: "Ajouter une adresse",
  R.titleHint.name: "Ajouter un titre",
  R.priceHint.name: "Ajouter un prix",
  R.comparePriceHint.name: "Ajouter un prix de comparaison",
  R.emailHint.name: "Ajouter un e-mail",
  R.linkHint.name: "Ajouter un lien",
  R.otherInfoHint.name: "Ajouter d'autre information",
  R.optionsHint.name: "Ajouter une options",
  R.countHint.name: "Ajouter un comptage",
  R.deliveryInfoHint.name: "Ajouter d'information sur la livraison",
  R.communicationMethod.name: "Méthode de communication",
  R.languageSkills.name: "Compétences linguistiques",
  R.identityInfo.name: "Informations d'identité",
  R.photo.name: "Photo",
  R.addProfilePhoto.name: "Ajouter une photo de profil",
  R.userProfileTempBlocked.name: "Le profil utilisateur n'est pas accessible pour le moment",
  R.someDayWriteBio.name: "Un jour écrire bio",
  R.unfollow.name: "Se desabonner",
  R.sendSms.name: "SMS code",
  R.missingPhoneNumber.name: "Numéro de téléphone manquant",
  R.pleaseAddPhoneNumber.name: "Veuillez ajouter un numéro de téléphone",
  R.pleaseAddProfilePhoto.name: "Veuillez ajouter une photo de profil",
  R.media.name: "Médias",
  R.biographyHint.name: "Ajouter une biographie",
  R.countryHint.name: "Ajouter un pays",
  R.categoryHint.name: "Ajouter une catégorie",
  R.addTags.name: "Ajouter uns balises",
  R.tagsHint.name: "ajouter un tag",
  R.tag.name: "Étiqueter",
  R.reject.name: "Rejeter",
  R.cameraPermissionDenied.name: "Autorisation de caméra refusée",
  R.pleaseGrantCameraPermission.name: "Veuillez autoriser la caméra",
  R.microphonePermissionDenied.name: "Autorisation du microphone refusée",
  R.pleaseGrantMicrophonePermission.name: "Veuillez accorder l'autorisation du microphone",
  R.needCameraMicrophonePermission.name:
      "Besoin d'une autorisation pour la caméra et le microphone",
  R.pleaseGrantCameraMicrophonePermission.name: "veuillez accorder la caméra et le microphone",
  R.grantPermission.name: "Donner la permission",
  R.callLogs.name: "Journaux d'appels",
  R.details.name: "Des détails",
  R.translations.name: "Traductions",
  R.rating.name: "Notation",
  R.message.name: "Message",
  R.video.name: "Vidéo",
  R.editImages.name: "Modifier les images",
  R.longPressChangeOrder.name: "Appuyez longuement sur l'image pour changer l'ordre",
  R.numberLimited.name: "Nombre limité",
  R.ifLeaveChangesDiscarded.name: "Les modifications non enregistrées seront ignorées",
  R.discard.name: "Jeter",
  R.kReturn.name: "Revenir",
  R.findingTranslatorEasy.name: "Trouver un traducteur facilement",
  R.connect.name: "Connecter",
  R.appointmentNotAvailable.name: "Rendez-vous non disponible",
  R.register.name: "S'inscrire",
  R.translatorApplicationUnderReview.name: "Candidature de traducteur en cours d'examen",
  R.translatorFired.name: "Traducteur viré",
  R.translatorSuspended.name: "Traducteur suspendu",
  R.contactUs.name: "Nous contacter",
  R.appeal.name: "Charme",
  R.kClass.name: "Classer",
  R.flash.name: "Éclair",
  R.type.name: "Taper",
  R.selectLanguages.name: "Sélectionnez les langues",
  R.complete.name: "Compléter",
  R.canceled.name: "Annulé",
  R.lookingForTranslator.name: "Cherche traducteur",
  R.connectWithClient.name: "Connectez-vous avec le client",
  R.currentSession.name: "Session actuelle",
  R.translationRequests.name: "Demandes de traduction",
  R.pleaseCompleteCurrentSession.name: "Veuillez terminer la session en cours",
  R.confirm.name: "Confirmer",
  R.enable.name: "Permettre",
  R.inApp.name: "InApp",
  R.duration.name: "Durée",
  R.addCall.name: "Ajouter un appel",
  R.reportIssue.name: "Signaler un problème",
  R.like.name: "J'aime",
  R.pass.name: "Non",
  R.congratulation.name: "Félicitation",
  R.chooseSource.name: "Choisissez la source",
  R.pleaseAddCurrency.name: "Veuillez ajouter une devise",
  R.currencyHint.name: "Ajouter une devise",
  R.address.name: "Adresse",
  R.addressHint.name: "Ajouter une adresse",
  R.subscriptions.name: "Abonnements",
  R.myProducts.name: "Mes produits",
  R.storeInfo.name: "Informations sur le magasin",
  R.additionalInfoHint.name: "Ajouter des informations complémentaires",
  R.salePrice.name: "Prix de vente",
  R.salePriceHint.name: "Ajouter un prix de vente",
  R.pleaseAddSalePrice.name: "Veuillez ajouter le prix de vente",
  R.storeItems.name: "Articles de magasin",
  R.addDescription.name: "Ajouter une description",
  R.selectCurrency.name: "Sélectionnez la devise",
  R.editStore.name: "Modifier le magasin",
  R.editProfilePhoto.name: "Modifier la photo de profil",
  R.oldItemsInterrogationDescription.name: "Description de l'interrogatoire des anciens objets",
  R.oldItemsPiling.name: "Les vieux objets s'entassent",
  R.swapThem.name: "Échangez-les",
  R.shareThemTitle.name: "Partagez-leur le titre",
  R.shareThemDescription.name: "Partagez leur description",
  R.oldItemsPilingTitle.name: "Titre d'empilement d'anciens objets",
  R.oldItemsPilingDescription.name: "Description de l'empilement d'anciens objets",
  R.findBestItemsAroundTitle.name: "Trouvez les meilleurs articles autour du titre",
  R.findBestItemsAroundDescription.name: "Trouvez les meilleurs articles autour de la description",
  R.matchChatExchangeTitle.name: "Faire correspondre le titre de l'échange de chat",
  R.matchChatExchangeDescription.name: "Faire correspondre la description de l'échange de chat",
  R.detail.name: "Détail",
  R.date.name: "Date",
  R.general.name: "Général",
  R.support.name: "Soutien",
  R.inviteFriend.name: "Inviter un ami",
  R.account.name: "Compte",
  R.yourProfile.name: "Votre profil",
  R.settingsBelow.name: "Ci-dessous vos paramètres",
  R.active.name: "Actif",
  R.inactive.name: "Inactif",
  R.matches.name: "Correspondance",
  R.matchesInfo.name:
      "Lorsque vous avez un article qu'une autre personne a aimé et vice versa, leurs articles apparaîtront ici",
  R.instantMatch.name: "Correspondance instantanée",
  R.instantMatchInfo.name:
      "Quand vous avez un article que quelqu'un d'autre a aimé, ses articles apparaîtront ici. Une fois que vous aimez de retour l'un des articles, vous serez instantanément assortis et vous pouvez commencer à discuter",
  R.mySwaps.name: "Mes échanges",
  R.item.name: "Article",
  R.declined.name: "Diminué",
  R.hideSwap.name: "Masquer l'échange",
  R.restoreSwap.name: "Restaurer l'échange",
  R.uploadingSwap.name: "Téléchargement de l'échange",
  R.updatingSwap.name: "Mise à jour de l'échange",
  R.locationDenied.name: "Emplacement refusé",
  R.enableLocation.name: "Location disponible",
  R.pleaseEnableLocation.name: "Veuillez activer la localisation",
  R.locationDeniedPermanently.name: "Localisation refusée définitivement",
  R.locationDisabled.name: "Localisation désactivée",
  R.privacy.name: "Confidentialité",
  R.update.name: "Mettre à jour",
  R.shareAppTitle.name: "Partager le titre de l'application",
  R.shareAppDescription.name: "Partager la description de l'application",
  R.chatNotFound.name: "Chat introuvable",
  R.addReply.name: "Ajouter une réponse",
  R.moreReplies.name: "Plus de réponses",
  R.reply.name: "Réponse",
  R.views.name: "Vues",
  R.blockedBy.name: "Bloqué par",
  R.blocked.name: "Bloqué",
  R.unblock.name: "Débloquer",
  R.acceptFriend.name: "Accepter ami",
  R.cancelFriendRequest.name: "Annuler la demande d'ami",
  R.friends.name: "Amis",
  R.requestFriend.name: "Demander un ami",
  R.declineFriendRequest.name: "Refuser la demande d'ami",
  R.sendFriendRequest.name: "Envoyer une demande d'ami",
  R.searchSettings.name: "Paramètres de recherche",
  R.addLocation.name: "Ajouter un emplacement",
  R.proposeSwap.name: "Proposer un échange",
  R.newMatch.name: "Nouveau match",
  R.foundNewMatch.name: "Vous avez trouvé une correspondance !!!",
  R.addCategory.name: "Ajouter une catégorie",
  R.contacts.name: "Contacts",
  R.following.name: "Abonnement",
  R.followers.name: "Abonnés",
  R.requests.name: "Demandes",
  R.invitations.name: "Invitations",
  R.blockedByUserDescription.name: "Bloqué par l'utilisateur",
  R.followBack.name: "S'abonner",
  R.accepted.name: "Accepté",
  R.shoppingNotAvailableInThisCountry.name: "Shopping non disponible dans ce pays",
  R.km.name: "KM",
  R.searchSwapsAroundTitle.name:
      "Ne perdez plus de temps et d'argent sur des achats non nécessaires. Une façon gratuite, amusante et interactive d'échanger",
  R.searchSwapsAroundDescription.name:
      "Recherchez des échanges autour de vous et échangez des articles avec des personnes de votre région",
  R.numOfItems.name: "Nombre d'articles",
  R.changeLocation.name: "Changer de lieu",
  R.addFirstSwapItemTitle.name: "Share Your First Item",
  R.addFirstSwapItemDescription.name:
      "Faites partie du premier réseau d'échange de Fibali en partageant votre premier article, téléchargez votre premier article maintenant!",
  R.checkOutThisSwapItem.name:
      "Rejoignez le premier réseau d'échange de Fibali et commencez à échanger dès maintenant!",
  R.noSwaps.name: "Aucun échange",
  R.commentInfoHint.name: "Ajouter un commentaire",
  R.commentInfo.name: "Commentaire",
  R.seeMore.name: "Voir plus",
  R.booking.name: "Réservation",
  R.tooltipSwapLocationButtonDescription.name:
      "Vous pouvez modifier la région de recherche d'articles ici.",
  R.tooltipSwapSettingsButtonDescription.name:
      "Sélectionnez la distance appropriée pour votre recherche ici.",
  R.tooltipSwapBoardButtonDescription.name:
      "Vous pouvez télécharger, gérer et vérifier vos articles ici.",
  R.tooltipSwapChatsButtonDescription.name:
      "Discutez avec d'autres utilisateurs et échangez vos articles ici.",
  R.tooltipSwapRewindButtonDescription.name:
      "Réinitialisez tous les éléments précédemment ignorés ici.",
  R.swapDeclined.name: "Échange refusé",
  R.swapAccepted.name: "Échange accepté",
  R.swapCanceled.name: "Échange annulé",
  R.addSwapReview.name: "Ajouter un avis",
  R.relation.name: "Relation",
  R.post.name: "Publication",
  R.orderEvent.name: "Commande mise à jour",
  R.translatorCall.name: "Appel du traducteur",
  R.newPostComment.name: "Nouveau commentaire",
  R.newPostLike.name: "Nouveau J'aime",
  R.newPost.name: "Nouvelle publication",
  R.newCommentReply.name: "Nouvelle réponse",
  R.friendRequest.name: "Demande d'ami",
  R.friendRequestAccepted.name: "Demande d'ami acceptée",
  R.newFollow.name: "Nouvelle abonnement",
  R.newSwapItemReview.name: "Nouveau commentaire",
  R.newSwapItemLike.name: "Nouveau J'aime",
  R.addFirstPost.name: "Nouveau dans Fibali ! Partagez ce que vous avez en tête.",
  R.privacyNSecurity.name: "Confidentialité et sécurité",
  R.deleteAccount.name: "Supprimer le compte",
  R.gallery.name: "Galerie",
  R.emptyNotificationsTitle.name: "Aucune notification",
  R.emptyNotificationsDescription.name: "Vous n'avez aucune nouvelle notification pour le moment",
  R.liked.name: "Aimé",
  R.report.name: "Signaler",
  R.lightMode.name: "Mode clair",
  R.brightness.name: "Luminosité",
  R.termsOfService.name: "Conditions d'utilisation",
  R.skipLogging.name: "Passer la connexion",
  R.termsAndConditions.name: "Termes et conditions",
  R.iAgreeToTheTermsAndConditions.name: "J'accepte les termes et conditions",
  R.viewTermsAndConditions.name: "Voir les termes et conditions",
  R.loggingIn.name: "Connexion",
  R.askAgreeTermsConditions.name:
      "Salutation!\\n\\nBienvenue sur Fibali, la nouvelle application qui vous met en relation avec des personnes souhaitant échanger des objets dont ils n'ont plus besoin.\\n\\nAvant de commencer à échanger, nous avons besoin que vous acceptiez nos termes et conditions. Ce sont des règles qui définissent vos droits et obligations en tant qu'utilisateur de notre application. Ils abordent également des questions importantes telles que les droits de propriété intellectuelle, la gestion des litiges et la conduite acceptable.\\n\\nEn acceptant nos termes et conditions, vous confirmez avoir lu, compris et accepté d'y être lié. Vous vous engagez également à respecter notre politique d'utilisation acceptable, qui est incorporée par référence dans nos termes et conditions.\\n\\nNos termes et conditions sont un contrat juridiquement contraignant entre vous et nous, veuillez donc les lire attentivement. Si vous avez des questions ou des préoccupations, veuillez nous contacter à l'adresse piicubic@gmail.com. Nous sommes heureux de vous aider.\\n\\nPour consulter nos termes et conditions, veuillez cliquer sur le lien ci-dessous. Pour les accepter et continuer à utiliser notre application, veuillez cocher la case et cliquer sur le bouton ci-dessous.",
  R.place.name: "Lieu",
  R.block.name: "Bloquer",
  R.blockUserDescription.name:
      "Êtes-vous sûr(e) de vouloir bloquer cet utilisateur ? Le blocage empêchera définitivement cette personne de vous contacter ou de voir votre profil. Cependant, vous pourrez la débloquer ultérieurement si vous changez d'avis.",
  R.blockedUsers.name: "Utilisateurs bloqués",
  R.noBlockedUsers.name: "Aucun utilisateur bloqué",
  R.oopsSomethingWentWrong.name: "Oops ! Quelque chose s'est mal passé.",
  R.unBlockUserDescription.name:
      "Êtes-vous sûr(e) de vouloir débloquer cet utilisateur ? Une fois débloqué(e), il pourra vous contacter et voir votre profil à nouveau.",
  R.userNotFound.name: "Utilisateur introuvable",
  R.blockedAt.name: "Bloqué le",
  R.youHaveBeenBlockedByThisUser.name: "Vous avez été bloqué(e) par cet utilisateur.",
  R.youHaveBlockedThisUser.name: "Vous avez bloqué cet utilisateur.",
  R.storeNotFound.name: "Magasin non trouvé",
  R.storeNotAvailable.name: "Magasin non disponible",
  R.about.name: "À propos",
  R.noPostHere.name: "Aucune publication ici",
  R.whyNotShare.name:
      "Pourquoi ne pas partager ce qui vous préoccupe et voir ce que les autres ont à dire ?",
  R.followOtherUsersAndGetUpdated.name:
      "Suivez d'autres utilisateurs et tenez-vous au courant de leurs dernières publications ici",
  R.likedPostsWillAppearHere.name: "Les publications aimées apparaîtront ici",
  R.commentedPostsWillAppearHere.name: "Les publications commentées apparaîtront ici",
  R.swapIntroDescription.name:
      "Trouvez et échangez les articles dont vous n'avez pas besoin contre ceux que vous voulez en un simple geste",
  R.connectIntroDescription.name:
      "Échangez des articles et des idées, partagez vos pensées et rencontrez de nouvelles personnes",
  R.fashion.name: "mode",
  R.beauty.name: "beauté",
  R.travel.name: "voyage",
  R.family.name: "famille",
  R.health.name: "santé",
  R.fitness.name: "fitness",
  R.music.name: "musique",
  R.movies.name: "films",
  R.specialEvents.name: "événements spéciaux",
  R.hobbies.name: "loisirs",
  R.technology.name: "technologie",
  R.homeDecor.name: "décoration d'intérieur",
  R.dIY.name: "bricolage",
  R.gardening.name: "jardinage",
  R.finance.name: "finance",
  R.studentLife.name: "vie étudiante",
  R.pets.name: "animaux de compagnie",
  R.currentNews.name: "actualités",
  R.science.name: "science",
  R.newUpdateAvailableTitle.name: "Nouvelle mise à jour disponible",
  R.newUpdateAvailableDescription.name:
      "Nous avons une nouvelle version disponible pour vous à télécharger. Veuillez mettre à jour vers la dernière version pour profiter des dernières fonctionnalités et améliorations.",
  R.notification.name: "notification",
  R.swipeRightDescription.name:
      "Faire glisser un article vers la droite signifie que vous l'aimez. Si son propriétaire aime également l'un de vos articles, vous serez mis en relation pour échange.",
  R.swipeLeftDescription.name:
      "Faire glisser un article vers la gauche signifie que vous n'êtes pas intéressé par celui-ci. Vous ne verrez plus cet article.",
  R.noChatsYetTitle.name: "Pas encore de discussions",
  R.noChatsYetDescription.name: "Ajoutez de nouveaux amis et commencez des conversations",
  R.whoCanMyPost.name: "Qui peut voir mon post ?",
  R.comment.name: "Commenter",
  R.needToLogin.name: "Vous devez vous connecter pout continuer",
  R.finishSwipingToSeeMore.name: "Faites glisser tous les éléments pour en voir plus",
  R.pleaseAllowAccessToGPSLocation.name:
      "Fibali a besoin d'accéder à votre position GPS pour vous montrer les articles à proximité",
  R.addPrice.name: "Ajouter un prix",
  R.deleteItemWarning.name: "Êtes-vous sûr(e) de vouloir supprimer cet article ?",
  R.cantReachNetwork.name: "Impossible de se connecter au réseau",
  R.pleaseCheckYourNetworkNTryAgain.name: "Veuillez vérifier votre connexion et réessayer.",
  R.noInternetConnection.name: "Pas de connexion Internet",
  R.viewedPostsWillAppearHere.name: "Les publications consultées apparaîtront ici",
  R.swapsWillAppearHere.name: "Les échanges apparaîtront ici",
  R.noComments.name: "Aucun commentaire",
  R.readMore.name: "Lire la suite",
  R.showLess.name: "Montrer moins",
  R.startingLiveVideo.name: "Démarrage de la vidéo en direct",
  R.liveVideoStarted.name: "Vidéo en direct démarrée",
  R.liveIsAlreadyStarting.name: "La vidéo en direct est déjà en cours de démarrage",
  R.startLiveStreaming.name: "Commencer un LIVE",
  R.myStores.name: "Mes magasins",
  R.stores.name: "Magasins",
  R.catalog.name: "Catalogue",
  R.postNotFound.name: "Publication introuvable",
  R.cantOpen.name: "Impossible d'ouvrir",
  R.remove.name: "Retirer",
  R.sevenDayReturnPolicy.name: "Droit de rétractation sous 7 jours",
  R.fourteenDayReturnPolicy.name: "Droit de rétractation sous 14 jours",
  R.thirtyDayReturnPolicy.name: "Droit de rétractation sous 30 jours",
  R.sixtyDayReturnPolicy.name: "Droit de rétractation sous 60 jours",
  R.ninetyDayReturnPolicy.name: "Droit de rétractation sous 90 jours",
  R.noReturnPolicy.name: "Aucun droit de rétractation",
  R.sevenDayReturnPolicySellerDescription.name:
      "Ce droit de rétractation est idéal pour les articles qui sont rapidement consommables ou ont une courte durée de conservation. Il offre à vos clients une semaine complète pour retourner le produit s'il ne répond pas à leurs attentes.",
  R.fourteenDayReturnPolicySellerDescription.name:
      "Cette politique est idéale pour les biens de consommation à rotation rapide. Il vous donne deux semaines pour retourner un produit s'il ne répond pas à vos attentes.",
  R.thirtyDayReturnPolicySellerDescription.name:
      "C'est la politique de retour la plus courante. Il vous donne un mois complet pour décider si vous voulez garder un produit.",
  R.sixtyDayReturnPolicySellerDescription.name:
      "Cette politique est moins courante mais peut être utilisée pour les articles de plus grande valeur dont vous pourriez avoir besoin de plus de temps pour évaluer.",
  R.ninetyDayReturnPolicySellerDescription.name:
      "C'est une politique de retour généreuse souvent utilisée par les entreprises qui ont une grande confiance dans leurs produits. Cela peut être un argument de vente fort pour les clients.",
  R.noReturnPolicySellerDescription.name:
      "Cet article est une vente finale et n'est pas éligible au retour. Cette politique est idéale pour les articles qui ne peuvent pas être revendus pour des raisons de santé ou d'hygiène, les articles faits sur mesure ou les articles en liquidation.",
  R.sevenDayReturnPolicyBuyerDescription.name:
      "Vous avez 7 jours pour retourner cet article pour un remboursement complet.",
  R.fourteenDayReturnPolicyBuyerDescription.name:
      "Vous avez 14 jours pour retourner cet article pour un remboursement complet.",
  R.thirtyDayReturnPolicyBuyerDescription.name:
      "Vous avez 30 jours pour retourner cet article pour un remboursement complet.",
  R.sixtyDayReturnPolicyBuyerDescription.name:
      "Vous avez 60 jours pour retourner cet article pour un remboursement complet.",
  R.ninetyDayReturnPolicyBuyerDescription.name:
      "Vous avez 90 jours pour retourner cet article pour un remboursement complet.",
  R.noReturnPolicyBuyerDescription.name: "Cet article n'est pas éligible au retour.",
  R.unusedAndInOriginalCondition.name: "État neuf et original",
  R.unusedAndInOriginalConditionSellerDescription.name:
      "Il s'agit d'une condition standard qui garantit que les articles sont retournés dans le même état qu'ils ont été reçus. Cela s'applique généralement aux articles non ouverts, aux produits dont les scellés sont intacts ou à ceux qui ne présentent aucun signe d'usure ou d'utilisation. Cela protège les vendeurs d'accepter des articles usagés ou endommagés pour les retours.",
  R.unusedAndInOriginalConditionBuyerDescription.name:
      "Pour retourner cet article, il doit être dans son état et emballage d'origine. Cela signifie qu'il doit être non ouvert, non utilisé et avec toutes les étiquettes et marques d'origine intactes. Veuillez vous assurer que l'article est soigneusement emballé pour éviter tout dommage pendant le retour.",
  R.defectiveOrDamaged.name: "Défectueux ou endommagé",
  R.defectiveOrDamagedSellerDescription.name:
      "Cette condition permet le retour des articles arrivés défectueux ou ayant développé un défaut dans un délai d'utilisation raisonnable. Elle couvre les défauts de fabrication, les dommages dus à l'expédition ou les dysfonctionnements qui se produisent dans des conditions normales d'utilisation. Cela protège les acheteurs de se retrouver avec des produits défectueux.",
  R.defectiveOrDamagedBuyerDescription.name:
      "Si votre article arrive défectueux ou développe un défaut dans un délai raisonnable, vous pouvez le retourner pour un remboursement complet ou un remplacement. Veuillez fournir des détails sur le défaut ou les dommages lors de la demande de retour.",
  R.notAsDescribed.name: "Non conforme à la description",
  R.notAsDescribedSellerDescription.name:
      "Cette condition permet le retour des articles qui diffèrent de manière significative de leur description ou des caractéristiques annoncées. Elle couvre les différences de taille, de couleur, de fonctionnalité ou d'autres caractéristiques essentielles. Cela protège les acheteurs des informations trompeuses ou inexactes sur les produits.",
  R.notAsDescribedBuyerDescription.name:
      "Vous pouvez retourner cet article s'il ne correspond pas à la description de l'annonce. Cela comprend les articles qui sont différents en taille, en couleur, en fonctionnalités ou en d'autres aspects importants par rapport à la description du produit. Veuillez fournir des détails sur les différences lors de la demande de retour.",
  R.inStoreExchanges.name: "Échanges en magasin",
  R.inStoreExchangesSellerDescription.name:
      "Permettez aux clients d'échanger leur article contre un autre dans votre magasin.",
  R.mailExchanges.name: "Échanges par courrier",
  R.mailExchangesSellerDescription.name:
      "Permettez aux clients de vous envoyer leur article par la poste pour un échange.",
  R.homeOfficeExchanges.name: "Échanges à domicile ou au bureau",
  R.homeOfficeExchangesSellerDescription.name:
      "Organisez la collecte de l'article directement à l'adresse du client par un coursier pour un échange.",
  R.shared.name: "Partagé",
  R.returnPolicy.name: "Politique de retour",
  R.returnPolicyDescription.name:
      "Une politique de retour indique aux clients le nombre de jours dont ils disposent pour retourner un article et obtenir un remboursement.",
  R.chooseReturnTimeFrame.name: "Choisir une politique de retour",
  R.acceptExchange.name: "Accepter les échanges",
  R.acceptExchangeDescription.name:
      "Précisez comment les clients peuvent échanger des articles. Vous pouvez choisir une ou plusieurs options.",
  R.conditions.name: 'Conditions',
  R.conditionsDescription.name:
      'Spécifiez les conditions que l\'article doit remplir pour être éligible à un retour.',
  R.noMoreProducts.name: "Pas plus de produits",
  R.global.name: "Global",
};
