import 'package:fibali/fibali_core/bloc/remote_config/remote_config_cubit.dart';

final appLocAR = {
  R.items.name: "الأغراض",
  R.messageSent.name: "تم الارسال",
  R.keywords.name: "العلامات",
  R.phoneNumber.name: "رقم الهاتف",
  R.province.name: "المحافظة",
  R.subProvince.name: "محافظة فرعية",
  R.updatingStoreInfo.name: "جارٍ تحديث معلومات المتجر ...",
  R.sellerReminderSent.name: "سيتلقى البائع تذكيرًا لإرسال الطلب",
  R.invalidPhoneNumber.name: "رقم الهاتف غير صحيح",
  R.locationUnknown.name: "الموقع غير معروف",
  R.creatingUser.name: "إنشاء المستخدم",
  R.quote.name: "يقتبس",
  R.unknown.name: "مجهول",
  R.share.name: "يشارك",
  R.editProfile.name: "تعديل الملف الشخصي",
  R.addItem.name: "اضافة اعلان",
  R.updateStoreInfo.name: "تحديث معلومات المتجر",
  R.logout.name: "تسجيل خروج",
  R.contactInfo.name: "اتصال",
  R.from.name: "من",
  R.all.name: "الجميع",
  R.send.name: "إرسال",
  R.mayBeLater.name: "ربما في وقت لاحق",
  R.quantity.name: "كمية",
  R.kickOf.name: "ركلة",
  R.search.name: "يبحث",
  R.magazin.name: "مجازين",
  R.price.name: "سعر",
  R.comparePrice.name: "قارن السعر",
  R.fillDescription.name: "يرجى ملء وصف اعلان",
  R.fillTitle.name: "الرجاء ملء عنوان اعلان",
  R.sellerBoard.name: "لوحة البائع",
  R.variants.name: "المتغيرات",
  R.addValue.name: "أضف قيمة واحدة على الأقل إلى",
  R.nineMax.name: "بحد أقصى 9 سمات",
  R.editItem.name: "تعديل عنصر",
  R.orderDetails.name: "تفاصيل الطلب",
  R.posts.name: "منشوراتي",
  R.camera.name: "آلة تصوير",
  R.submit.name: "يُقدِّم",
  R.alreadyReviewd.name: "مراجعة بالفعل!",
  R.saveNDefault.name: "حفظ وتعيين الافتراضي",
  R.missingAddress.name: "عنوان التسليم مفقود",
  R.pleaseUpdateAddress.name: "يرجى تحديث العنوان",
  R.total.name: "المجموع:",
  R.onlyAlgeria.name: "فقط الجزائر متاحة الآن!",
  R.checkPhone.name: "تحقق من الهاتف",
  R.getSms.name: "احصل على الرسائل القصيرة",
  R.streaming.name: "عندما يعجب المستخدم بأحد أغراضك ، ستظهر أغراضه هنا.",
  R.fillOTP.name: "املأ كلمة المرور لمرة واحدة",
  R.streetAddress.name: "عنوان الشارع",
  R.addStreetAddress.name: "أضف عنوان الشارع",
  R.addDeliveryAddress.name: "أضف عنوان التسليم",
  R.editDeliveryAddress.name: "تحرير عنوان التسليم",
  R.addPhoneNumber.name: "أضف رقم الهاتف",
  R.updateAddress.name: "تحديث العنوان",
  R.deliveryAddress.name: "توصيل",
  R.title.name: "عنوان",
  R.sixDigitsOTP.name: "الرجاء إدخال كود مكون من 6 أرقام من الرسائل القصيرة",
  R.code.name: "شفرة",
  R.checkCode.name: "التحقق من الشفرة",
  R.setting.name: "ضبط",
  R.distance.name: "مسافه: بعد",
  R.news.name: "أخبار",
  R.strictSearchMode.name: "وضع البحث الصارم",
  R.oops.name: "تبا شيء ما حدث بشكل خاطئ. يرجى التحقق من الشبكة الخاصة بك وحاول مرة أخرى.",
  R.likeItem.name: "مثل البند",
  R.noItems.name: "يبدو أنه لا توجد أغراض حولك ، حاول تغيير منطقة البحث أو توسيعها.",
  R.shareWithFriends.name: "أو شارك التطبيق مع أصدقائك وابدأ في التبديل معهم.",
  R.reload.name: "إعادة تحميل",
  R.giveAway.name: "يتبرع",
  R.edit.name: "يحرر",
  R.notifications.name: "إشعارات",
  R.delete.name: "حذف",
  R.chat.name: "دردشة",
  R.match.name: "تبادل",
  R.done.name: "فعله",
  R.skip.name: "يتخطى",
  R.itemsInfo.name: "هذه هي الاغراض التي أضفتها إلى قائمة التبادل الخاصة بك",
  R.passItem.name: "تمرير البند",
  R.profile.name: "الملف الشخصي",
  R.location.name: "الموقع",
  R.regions.name: "المناطق",
  R.selected.name: "المحدد",
  R.selectLocation.name: "حدد موقع الخريطة",
  R.openingNewStore.name: "جارٍ فتح متجر جديد ...",
  R.selectRegions.name: "حدد المناطق",
  R.selectCategories.name: "حدد الفئات",
  R.searchHere.name: "ابحث هنا",
  R.apply.name: "يتقدم",
  R.numOrders.name: "عدد الطلبات",
  R.soo9Choice.name: "SOO9 اختيار",
  R.sortedBy.name: "مرتبة حسب",
  R.numLikes.name: "عدد الإعجابات",
  R.sort.name: "فرز",
  R.addMapLocation.name: "أضف موقع الخريطة",
  R.country.name: "دولة",
  R.geoLocation.name: "الموقع الجغرافي",
  R.select.name: "يختار",
  R.aMomentAgo.name: "منذ لحظة",
  R.error.name: "خطأ",
  R.other.name: "آخر",
  R.messages.name: "رسائل",
  R.letsSwap.name: "هيا بنا نقايض",
  R.order.name: "ترتيب",
  R.received.name: "تلقى",
  R.pending.name: "قيد الانتظار",
  R.clientOrders.name: "طلبات العميل",
  R.frequentlyAskedQuestions.name: "أسئلة مكررة",
  R.sellerOrders.name: "طلبات البائع",
  R.titleInfo.name: "سيكون هذا هو الاسم الرئيسي الذي سيظهر في البحث",
  R.noOrders.name: " ليس لديك أوامر",
  R.orders.name: "طلبات",
  R.recieved.name: "تم الاستلام",
  R.reminder.name: "تذكير",
  R.refund.name: "استرداد",
  R.addStore.name: "أضف المتجر",
  R.addFavorite.name: "أصنع معروف",
  R.ownedItem.name: "لا يمكنك طلب عنصر تملكه",
  R.ok.name: "نعم",
  R.avgReview.name: "استعراض متوسط",
  R.review.name: "إعادة النظر",
  R.acceptRefund.name: "قبول رد الأموال",
  R.declineRefund.name: "رفض الاسترداد",
  R.client.name: "عميل",
  R.seller.name: "تاجر",
  R.sendPackage.name: "إرسال الحزمة",
  R.deliveryInfo.name: "معلومات التوصيل",
  R.loggingOut.name: "تسجيل الخروج...",
  R.createNewStore.name: "إنشاء متجر جديد",
  R.fillCurrency.name: "عملة التعبئة",
  R.checkOrder.name: "تحقق من الطلب",
  R.info.name: "معلومات",
  R.stats.name: "احصائيات",
  R.additionalInfo.name: "معلومات اضافية",
  R.contactClientService.name: "خدمة العملاء",
  R.orderID.name: "رقم التعريف الخاص بالطلب:",
  R.checkAddress.name:
      "معلومات عنوان التسليم غير مكتملة. يرجى تحديث المعلومات الخاصة بك قبل تقديم الطلب.",
  R.count.name: "عدد",
  R.hideItem.name: "إخفاء اعلان",
  R.restoreItem.name: "قم باستعادة اعلان",
  R.pleaseLogIn.name: "الرجاء تسجيل الدخول / تسجيل الدخول",
  R.logIn.name: "تسجيل الدخول",
  R.updateInfo.name: "تحديث المعلومات",
  R.description.name: "وصف",
  R.uploadItem.name: "تحميل البند",
  R.existAlready.name: "موجود بالفعل",
  R.empty.name: "فارغة",
  R.add.name: "يضيف",
  R.fillPrice.name: "سعر التعبئة",
  R.likes.name: "الإعجابات",
  R.swaps.name: "المقايضات",
  R.accept.name: "قبول",
  R.failed.name: "باءت بالفشل",
  R.currency.name: "عملة",
  R.newItem.name: "عنصر جديد",
  R.markAsSwapped.name: "وضع علامة كمبادلة",
  R.decline.name: "انخفاض",
  R.viewAll.name: "عرض الكل>",
  R.fAQ.name: "التعليمات.",
  R.homePage.name: "مسكن",
  R.allItems.name: "كل الاشياء",
  R.pleaseFillName.name: "يرجى ملء اسمك أولا",
  R.addKeyword.name: "الرجاء إضافة كلمة رئيسية واحدة على الأقل",
  R.name.name: "اسم",
  R.continu.name: "يكمل",
  R.addImages.name: "إضافة الصور",
  R.addLogo.name: "أضف صورة الشعار",
  R.addBackgroundImage.name: "أضف صورة الخلفية",
  R.sixImagesMax.name: "6 صور كحد أقصى",
  R.itemInfo.name: "معلومات اعلان",
  R.uploadingItem.name: "جارٍ تحميل اعلان ...",
  R.alreadySubmitting.name: "يتم الإرسال بالفعل",
  R.failedLoadingItem.name: " فشل تحميل اعلان",
  R.addOneImage.name: "أضف صورة واحدة على الأقل",
  R.pleaseAddLogo.name: "الرجاء إضافة صورة شعار",
  R.pleaseAddBackground.name: "الرجاء إضافة صورة الخلفية",
  R.createNewItem.name: "إنشاء عنصر جديد",
  R.email.name: "البريد الإلكتروني",
  R.link.name: "نهاية لهذه الغاية",
  R.otherInfo.name: "معلومات اخرى",
  R.source.name: "مصدر",
  R.filters.name: "المرشحات",
  R.category.name: "فئة",
  R.categories.name: "فئات",
  R.moments.name: "لحظات",
  R.contact.name: "اتصال",
  R.reviews.name: "المراجعات",
  R.saleServices.name: "خدمات البيع",
  R.paymentOptions.name: "خيارات الدفع",
  R.addSubCategory.name: "أضف فئة فرعية",
  R.addNote.name: "اضف ملاحظة",
  R.submittingOrder.name: "تقديم الطلب",
  R.success.name: "النجاح",
  R.selectOption.name: "حدد الخيار",
  R.becomeSeller.name: "كيف تصبح بائعا",
  R.save.name: "حفظ",
  R.openNewStore.name: "افتح متجرًا جديدًا",
  R.sendingReminder.name: "إرسال تذكير ...",
  R.applyingRefund.name: "طلب استرداد ...",
  R.addingReview.name: "إضافة مراجعة ...",
  R.openingStore.name: "جارٍ فتح المتجر ...",
  R.updatingAddress.name: "جارٍ تحديث العنوان ...",
  R.loading.name: "جار التحميل...",
  R.checkOutThisItem.name: "checkOutThisItemEN",
  R.bestShopping.name: "أفضل تجربة تسوق",
  R.bestShoppingDescription.name:
      "اعثر على أفضل الصفقات عبر الإنترنت لمنتجات الأجهزة المنزلية والمجوهرات والساعات والمكملات الغذائية والعناية بالبشرة وغير ذلك الكثير.",
  R.fastDelivery.name: "توصيل سريع",
  R.fastDeliveryDescription.name:
      "أصبح التسوق عبر الإنترنت ممتعًا فقط بسبب منصتنا. نقوم بتسليم المنتجات في جميع أنحاء البلاد ، مما يسهل العملاء.",
  R.cod.name: "دفع امن",
  R.codDescription.name:
      "نقدم أسهل طرق الدفع مثل الدفع نقدًا عند الاستلام وبطاقة الائتمان وبطاقة الائتمان عند التسليم.",
  R.greatCustomerService.name: "خدمة عملاء رائعة",
  R.awesomeAfterSales.name: "رهيبة بعد البيع",
  R.excellentProducts.name: "مجموعة ممتازة من المنتجات",
  R.competitivePrices.name: "أسعار منافسة",
  R.haveItAll.name: "لدينا كل شيء !!!",
  R.tenImagesMax.name: "10 صور كحد أقصى",
  R.pleaseAddTitle.name: "الرجاء إضافة عنوان جذاب لإشراك العملاء",
  R.pleaseAddDescription.name: "الرجاء إضافة وصف للعنصر الخاص بك.",
  R.pleaseAddAdditionalInfo.name:
      "يمكنك إضافة معلومات إضافية حول البند الخاص بك. (سياسة الإرجاع ، شروط التسليم ، الضمان ... إلخ.",
  R.pleaseAddCategory.name: "الرجاء اختيار الفئة التي ينتمي إليها البند الخاص بك.",
  R.pleaseAddTags.name:
      "الرجاء إضافة علامات البحث. (مثال لبنك الطاقة: بنك الطاقة ، البطارية ، الشاحن ، ... إلخ).",
  R.itemPhotos.name: "صور اعلان",
  R.pleaseAddItemPhotos.name:
      "الرجاء تحميل الصور من البند الخاص بك. (سيتم عرض هذه الصور في الأعلى).",
  R.additionalItemPhotos.name: "صور إضافية",
  R.pleaseAddAdditionalItemPhotos.name:
      "يرجى تحميل صور وصفية إضافية. (مثال: دليل المستخدم ، الضمانات ، الترويج إلخ.).",
  R.options.name: "خيارات",
  R.pleaseAddOption.name: "الرجاء إضافة خيارات التخصيص. (مثال: اللون ، الحجم ، الوزن ...).",
  R.pleaseAddPrice.name:
      "الرجاء إضافة السعر الأساسي لمنتجك. (إذا كانت لديك أسعار محددة لخيارات أغراض مختلفة ، يمكنك إضافتها في خيارات التخصيص).",
  R.pleaseAddComparePrice.name: "يمكنك إضافة سعر مقارنة مفيد لإظهار السعر القديم على سبيل المثال.",
  R.supplierInfo.name: "معلومات المورد",
  R.pleaseAddSupplierInfo.name:
      "يمكنك إضافة معلومات حول المورد الخاص بك هنا. لن تتم مشاركة هذه المعلومات مع العملاء (يمكنك فقط رؤيتها).",
  R.subOptions.name: "خيارات فرعية",
  R.pleaseAddSubOptions.name:
      "الرجاء إضافة الخيارات الفرعية المتاحة. (مثال: أحمر ، أزرق ، أخضر ...).",
  R.updatingItem.name: "جارٍ تحديث اعلان ...",
  R.callDetails.name: "تفاصيل",
  R.callID.name: "ID",
  R.noCalls.name: "لا مكالمات",
  R.newOrder.name: "طلب جديد",
  R.remindSeller.name: "تذكير البائع",
  R.orderReceived.name: "طلب وارد",
  R.refundApplication.name: "طلب الاسترداد",
  R.itemPackaged.name: "البند معبأة",
  R.packageSent.name: "تم إرسال الطرد",
  R.confirmOrder.name: "تم تاكيد الطلب",
  R.addReview.name: "تمت إضافة المراجعة",
  R.uploadingPost.name: "تحميل المنشور",
  R.updatingPost.name: "تحديث المنشور",
  R.hidePost.name: "اخفاء المنشور",
  R.restorePost.name: "استعادة المنشور",
  R.subSubProvince.name: "المنطقة الفرعية",
  R.tagLocation.name: "العلامة",
  R.createPost.name: "إنشاء المنشور",
  R.upload.name: "تحميل",
  R.comments.name: "تعليقات",
  R.submittingComment.name: "تقديم تعليق",
  R.checkOutThisPost.name: "تحقق من هذا المنصب",
  R.addComment.name: "أضف تعليق",
  R.cancel.name: "بطل",
  R.businesses.name: "الأعمال",
  R.clients.name: "عملاء",
  R.registerBusiness.name: "تسجيل الأعمال",
  R.back.name: "خلف",
  R.storeName.name: "اسم المتجر",
  R.firstName.name: "الاسم الاول",
  R.lastName.name: "الكنية",
  R.fillStoreInfoDescription.name: "ملء وصف معلومات المتجر",
  R.fillAuthorInfoDescription.name: "املأ وصف معلومات المؤلف",
  R.fillStoreLocationDescription.name: "ملء وصف موقع المتجر",
  R.registration.name: "تسجيل",
  R.fillLanguageSkills.name: "أكمل المهارات اللغوية",
  R.fillIdentityInfo.name: "املأ معلومات الهوية",
  R.fillWorkRegion.name: "قم بتعبئة منطقة العمل",
  R.hourlyRate.name: "المعدل بالساعة",
  R.addPhoto.name: "إضافة صورة",
  R.sendJobApplication.name: "أرسل طلب الوظيفة",
  R.selectLanguage.name: "اختار اللغة",
  R.english.name: "إنجليزي",
  R.arabic.name: "عربي",
  R.french.name: "فرنسي",
  R.chinese.name: "صينى",
  R.next.name: "التالي",
  R.discover.name: "اكتشف",
  R.store.name: "متجر",
  R.nearby.name: "مجاور",
  R.follow.name: "يتبع",
  R.home.name: "مسكن",
  R.translators.name: "المترجمين",
  R.urgency.name: "الاستعجال",
  R.accountSecurity.name: "أمن الحساب",
  R.privacySettings.name: "إعدادات الخصوصية",
  R.notificationSettings.name: "إعدادات الإشعار",
  R.generalSettings.name: "الاعدادات العامة",
  R.fontSize.name: "حجم الخط",
  R.darkMode.name: "الوضع المظلم",
  R.helpCenter.name: "مركز المساعدة",
  R.appreciation.name: "تقدير",
  R.links.name: "الروابط",
  R.workWithUs.name: "اعمل معنا",
  R.aboutUs.name: "معلومات عنا",
  R.personalInformation.name: "معلومات شخصية",
  R.history.name: "تاريخ",
  R.cart.name: "عربة التسوق",
  R.coupons.name: "كوبونات",
  R.wishList.name: "قائمة الرغبات",
  R.vip.name: "كبار الشخصيات",
  R.guidelines.name: "القواعد الارشادية",
  R.version.name: "إصدار",
  R.termsOfUse.name: "شروط الاستخدام",
  R.privacyTerms.name: "شروط الخصوصية",
  R.addBiography.name: "أضف سيرة ذاتية لمساعدة الناس على التعرف عليك",
  R.chooseLocation.name: "اختر موقعا",
  R.selectGender.name: "اختر الجنس",
  R.selectBirthDay.name: "حدد يوم ميلادك",
  R.editBiography.name: "تحرير السيرة الذاتية",
  R.gender.name: "جنس",
  R.birthDate.name: "تاريخ الميلاد",
  R.biography.name: "سيرة شخصية",
  R.settings.name: "إعدادات",
  R.help.name: "مساعدة",
  R.scan.name: "مسح",
  R.algeria.name: "الجزائر",
  R.morroco.name: "المغرب",
  R.tunisia.name: "تونس",
  R.egypt.name: "مصر",
  R.language.name: "لغة",
  R.editName.name: "تعديل الاسم",
  R.selectCountry.name: "حدد الدولة",
  R.editBirthday.name: "تحرير تاريخ الميلاد",
  R.female.name: "أنثى",
  R.male.name: "ذكر",
  R.scheduledTranslation.name: "الترجمة المجدولة",
  R.currentTranslation.name: "الترجمة الحالية",
  R.online.name: "متصل",
  R.offline.name: "غير متصل على الانترنت",
  R.to.name: "ل",
  R.startDate.name: "تاريخ البدء",
  R.time.name: "وقت",
  R.endDate.name: "تاريخ الانتهاء",
  R.selectDate.name: "حدد تاريخ",
  R.by.name: "بواسطة",
  R.selectMethod.name: "حدد الطريقة",
  R.translatorClass.name: "فئة المترجم",
  R.searchTranslator.name: "البحث في المترجم",
  R.phone.name: "هاتف",
  R.number.name: "رقم",
  R.becomeExpert.name: "كن خبير فيبالي",
  R.downloadExpertApp.name: "يرجى تنزيل تطبيق الخبراء الخاص بنا",
  R.topTranslators.name: "كبار المترجمين",
  R.languages.name: "اللغات",
  R.findTranslator.name: "ابحث عن مترجمك",
  R.bestTranslatorsCatalog.name: "كتالوج أفضل المترجمين",
  R.myPreviousTranslationSessions.name: "جلسات الترجمة السابقة",
  R.translationDetails.name: "تفاصيل الترجمة",
  R.shopping.name: "التسوق",
  R.china.name: "الصين",
  R.personal.name: "الشخصية",
  R.business.name: "اعمال",
  R.hotels.name: "الفنادق",
  R.rental.name: "تأجير",
  R.flights.name: "الرحلات الجوية",
  R.experts.name: "خبراء",
  R.doctors.name: "الأطباء",
  R.gabi.name: "جابي",
  R.food.name: "طعام",
  R.swap.name: "تبادل",
  R.workUnderProgress.name: "العمل قيد الانجاز",
  R.comingSoon.name: "قريبا",
  R.supplier.name: "المورد",
  R.supplierSupplierDescription.name: "وصف المورد المورد",
  R.onlineShop.name: "متجر على الانترنت",
  R.onlineShopBusinessDescription.name: "وصف عمل متجر على الإنترنت",
  R.housing.name: "الإسكان",
  R.housingBusinessDescription.name: "وصف أعمال الإسكان",
  R.xiaoYi.name: "شياويي",
  R.xiaoYiBusinessDescription.name: "وصف العمل شياويى",
  R.carRental.name: "تاجير سيارة",
  R.carRentalBusinessDescription.name: "وصف أعمال تأجير السيارات",
  R.foodDelivery.name: "توصيل طلبات الطعام",
  R.foodDeliveryBusinessDescription.name: "وصف عمل توصيل الطعام",
  R.medical.name: "طبي",
  R.medicalBusinessDescription.name: "وصف العمل الطبي",
  R.connectClient.name: "تواصل مع العميل",
  R.call.name: "يتصل",
  R.pleaseAddBio.name: "الرجاء إضافة السيرة الذاتية",
  R.addLanguage.name: "إضافة لغة",
  R.acceptOnlineTranslation.name: "قبول الترجمة عبر الإنترنت",
  R.acceptOfflineTranslation.name: "اقبل الترجمة بلا إنترنت",
  R.addMinTwoTranslationLanguages.name: "أضف لغتي ترجمة على الأقل",
  R.addTranslatorBiography.name: "أضف سيرة المترجم",
  R.hourlyRateHint.name: "اضف سعر الساعة",
  R.firstNameHint.name: "اضف الاسم الأول",
  R.lastNameHint.name: "اضف الاسم الأخير",
  R.storeNameHint.name: "اضف اسم المتجر",
  R.descriptionHint.name: "اضف الوصف",
  R.keywordsHint.name: "اضف الكلمات الرئيسية",
  R.nameHint.name: "اضف الاسم",
  R.streetAddressHint.name: "اضف عنوان الشارع",
  R.titleHint.name: "اضف العنوان",
  R.priceHint.name: "اضف السعر",
  R.comparePriceHint.name: "قارن اضف السعر",
  R.emailHint.name: "اضف البريد الإلكتروني",
  R.linkHint.name: "اضف الارتباط",
  R.otherInfoHint.name: "اضف معلومات أخرى",
  R.optionsHint.name: "اضف الخيارات",
  R.countHint.name: "عد تلميح",
  R.deliveryInfoHint.name: "اضف معلومات التسليم",
  R.communicationMethod.name: "طريقة الاتصال",
  R.languageSkills.name: "مهارات اللغة",
  R.identityInfo.name: "معلومات الهوية",
  R.photo.name: "صورة",
  R.addProfilePhoto.name: "إضافة صورة الشخصي",
  R.userProfileTempBlocked.name: "لا يمكن الوصول إلى ملف تعريف المستخدم في الوقت الحالي",
  R.someDayWriteBio.name: "يوما ما اكتب السيرة الذاتية",
  R.unfollow.name: "الغاء المتابعة",
  R.sendSms.name: "أرسل كود",
  R.missingPhoneNumber.name: "رقم الهاتف مفقود",
  R.pleaseAddPhoneNumber.name: "الرجاء إضافة رقم الهاتف",
  R.pleaseAddProfilePhoto.name: "الرجاء إضافة صورة الملف الشخصي",
  R.media.name: "وسائل الإعلام",
  R.biographyHint.name: "اضف السيرة الذاتية",
  R.countryHint.name: "اضف البلد",
  R.categoryHint.name: "اضف الفئة",
  R.addTags.name: "اضف اشارة",
  R.tagsHint.name: "اضف العلامات",
  R.tag.name: "بطاقة شعار",
  R.reject.name: "يرفض",
  R.cameraPermissionDenied.name: "تم رفض إذن الكاميرا",
  R.pleaseGrantCameraPermission.name: "يرجى منح إذن الكاميرا",
  R.microphonePermissionDenied.name: "تم رفض إذن الميكروفون",
  R.pleaseGrantMicrophonePermission.name: "الرجاء منح إذن الميكروفون",
  R.needCameraMicrophonePermission.name: "تحتاج إذن الكاميرا والميكروفون",
  R.pleaseGrantCameraMicrophonePermission.name: "يرجى منح الكاميرا والميكروفون",
  R.grantPermission.name: "يعطي الأذن",
  R.callLogs.name: "سجلات المكالمات",
  R.details.name: "تفاصيل",
  R.translations.name: "الترجمات",
  R.rating.name: "تقييم",
  R.message.name: "رسالة",
  R.video.name: "فيديو",
  R.editImages.name: "تحرير الصور",
  R.longPressChangeOrder.name: "اضغط مطولاً على الصورة لتغيير الترتيب",
  R.numberLimited.name: "عدد محدود",
  R.ifLeaveChangesDiscarded.name: "سيتم تجاهل التغييرات التي لم يتم حفظها",
  R.discard.name: "تجاهل",
  R.kReturn.name: "يعود",
  R.findingTranslatorEasy.name: "العثور على مترجم سهل",
  R.connect.name: "تواصل",
  R.appointmentNotAvailable.name: "الموعد غير متوفر",
  R.register.name: "يسجل",
  R.translatorApplicationUnderReview.name: "طلب المترجم قيد المراجعة",
  R.translatorFired.name: "أطلق المترجم",
  R.translatorSuspended.name: "توقف المترجم",
  R.contactUs.name: "اتصل بنا",
  R.appeal.name: "جاذبية",
  R.kClass.name: "فصل",
  R.flash.name: "فلاش",
  R.type.name: "يكتب",
  R.selectLanguages.name: "حدد اللغات",
  R.complete.name: "اكتمال",
  R.canceled.name: "ألغيت",
  R.lookingForTranslator.name: "أبحث عن مترجم",
  R.connectWithClient.name: "تواصل مع العميل",
  R.currentSession.name: "الجلسة الحالية",
  R.translationRequests.name: "طلبات الترجمة",
  R.pleaseCompleteCurrentSession.name: "الرجاء إكمال الجلسة الحالية",
  R.confirm.name: "يتأكد",
  R.enable.name: "يُمكَِن",
  R.inApp.name: "InApp",
  R.duration.name: "مدة",
  R.addCall.name: "أضف مكالمة",
  R.reportIssue.name: "قضية تقرير",
  R.like.name: "يحب",
  R.pass.name: "يمر",
  R.congratulation.name: "تهنئة",
  R.chooseSource.name: "اختر المصدر",
  R.pleaseAddCurrency.name: "الرجاء إضافة العملة",
  R.currencyHint.name: "اضف العملة",
  R.address.name: "تبوك",
  R.addressHint.name: "اضف العنوان",
  R.subscriptions.name: "الاشتراكات",
  R.myProducts.name: "منتجاتي",
  R.storeInfo.name: "معلومات المتجر",
  R.additionalInfoHint.name: "اضف معلومات إضافية",
  R.salePrice.name: "سعر البيع",
  R.salePriceHint.name: "اضف سعر البيع",
  R.pleaseAddSalePrice.name: "الرجاء إضافة سعر البيع",
  R.storeItems.name: "تخزين الأغراض",
  R.addDescription.name: "اضف وصفا",
  R.selectCurrency.name: "اختر العملة",
  R.editStore.name: "تحرير المتجر",
  R.editProfilePhoto.name: "تحرير صورة الملف الشخصي",
  R.oldItemsInterrogationDescription.name: "وصف استجواب الأغراض القديمة",
  R.oldItemsPiling.name: "الأغراض القديمة تتراكم",
  R.swapThem.name: "قم بمبادلتها",
  R.shareThemTitle.name: "شاركهم العنوان",
  R.shareThemDescription.name: "شاركهم الوصف",
  R.oldItemsPilingTitle.name: "الأغراض القديمة تتراكم العنوان",
  R.oldItemsPilingDescription.name: "الأغراض القديمة تتراكم الوصف",
  R.findBestItemsAroundTitle.name: "ابحث عن أفضل الأغراض حول العنوان",
  R.findBestItemsAroundDescription.name: "البحث عن أفضل الأغراض حول الوصف",
  R.matchChatExchangeTitle.name: "تبادل تبادل الدردشة العنوان",
  R.matchChatExchangeDescription.name: "تطابق وصف تبادل الدردشة",
  R.detail.name: "التفاصيل",
  R.date.name: "تاريخ",
  R.general.name: "عام",
  R.support.name: "الدعم",
  R.inviteFriend.name: "ادعُ صديقًا",
  R.account.name: "حساب",
  R.yourProfile.name: "ملفك الشخصي",
  R.settingsBelow.name: "فيما يلي الإعدادات الخاصة بك",
  R.active.name: "نشيط",
  R.inactive.name: "غير نشط",
  R.matches.name: "تطابق",
  R.matchesInfo.name: "ندما يكون لديك اغراض أعجب شخص آخر والعكس صحيح ، ستظهر اغراضهم هنا",
  R.instantMatch.name: "تبادل فوري",
  R.instantMatchInfo.name:
      "عندما يكون لديك اغراض أحبها شخص آخر ، ستظهر اغراضه هنا. بمجرد أن تحب أحد اغراضه، ستتم مطابقتكما على الفور ويمكنك البدء في الدردشة",
  R.mySwaps.name: "مقايضات",
  R.item.name: "غرض",
  R.declined.name: "انخفض",
  R.hideSwap.name: "إخفاء المبادلة",
  R.restoreSwap.name: "استعادة المبادلة",
  R.uploadingSwap.name: "تحميل المبادلة",
  R.updatingSwap.name: "تحديث المبادلة",
  R.locationDenied.name: "مرفوض GPSموقع ال",
  R.enableLocation.name: "تمكين موقع",
  R.pleaseEnableLocation.name: "GPSالرجاء تفعيل ال",
  R.locationDeniedPermanently.name: "الموقع مرفوض بشكل دائم",
  R.locationDisabled.name: "معطل GPSموقع ال",
  R.privacy.name: "خصوصية",
  R.update.name: "تحديث",
  R.shareAppTitle.name: "مشاركة عنوان التطبيق",
  R.shareAppDescription.name: "وصف مشاركة التطبيق",
  R.chatNotFound.name: "لم يتم العثور على الدردشة",
  R.addReply.name: "إضافة الرد",
  R.moreReplies.name: "المزيد من الردود",
  R.reply.name: "رد",
  R.views.name: "الآراء",
  R.blockedBy.name: "حظر من قبل",
  R.blocked.name: "ممنوع",
  R.unblock.name: "رفع الحظر",
  R.acceptFriend.name: "قبول صديق",
  R.cancelFriendRequest.name: "إلغاء طلب الصداقة",
  R.friends.name: "اصحاب",
  R.requestFriend.name: "طلب صديق",
  R.declineFriendRequest.name: "رفض طلب الصداقة",
  R.sendFriendRequest.name: "ارسل طلب صداقة",
  R.searchSettings.name: "إعدادات البحث",
  R.addLocation.name: "أضف الموقع",
  R.proposeSwap.name: "اقترح مقايضة",
  R.newMatch.name: "تبادل جديد",
  R.foundNewMatch.name: "لقد وجدت تطابق !!!",
  R.addCategory.name: "إضافة فئة",
  R.contacts.name: "جهات الاتصال",
  R.following.name: "متابعات",
  R.followers.name: "متابعون",
  R.requests.name: "الطلبات",
  R.invitations.name: "الدعوات",
  R.blockedByUserDescription.name: "ممنوع بواسطة وصف المستخدم",
  R.followBack.name: "تابع ما سبق",
  R.accepted.name: "وافقت",
  R.shoppingNotAvailableInThisCountry.name: "التسوق غير متوفر في هذا البلد",
  R.km.name: "KM",
  R.searchSwapsAroundTitle.name: "الطريقة الأسهل والأكثر ملاءمة لتبادل الأغراض الخاصة بك",
  R.searchSwapsAroundDescription.name:
      "لا مزيد من إضاعة الوقت والمال على المشتريات غير الضرورية. طريقة مجانية وممتعة وتفاعلية لتبادل الأغراض مع الآخرين في المجتمع",
  R.numOfItems.name: "عدد الأغراض",
  R.changeLocation.name: "تحديد الموقع",
  R.addFirstSwapItemTitle.name: "شارك أغراضك",
  R.addFirstSwapItemDescription.name:
      "كن جزءًا من شبكة المبادلة الرائدة في Fibali من خلال مشاركة أول أغراضك ، قم بتحميل أغراضك الآن!",
  R.checkOutThisSwapItem.name: "انضم إلى شبكة المبادلة الرائدة في Fibali ، وابدأ في التبادل الآن!",
  R.noSwaps.name: "لا توجد مقايضات هنا",
  R.commentInfoHint.name: "أضف تعليق",
  R.commentInfo.name: "تعليق",
  R.seeMore.name: "شاهد المزيد",
  R.booking.name: "الحجز",
  R.tooltipSwapLocationButtonDescription.name: "يمكنك تغيير منطقة بحث الأغراض هنا.",
  R.tooltipSwapSettingsButtonDescription.name: "حدد المسافة المناسبة لبحثك هنا.",
  R.tooltipSwapBoardButtonDescription.name: "يمكنك تحميل وإدارة والتحقق من أغراضك هنا.",
  R.tooltipSwapChatsButtonDescription.name: "الدردشة مع المستخدمين الآخرين وتبادل الأغراض هنا.",
  R.tooltipSwapRewindButtonDescription.name: "إعادة تعيين جميع الأغراض التي تم تخطيها مسبقًا هنا.",
  R.swapDeclined.name: "مرفوضة",
  R.swapAccepted.name: "مقبول",
  R.swapCanceled.name: "ملغاة",
  R.addSwapReview.name: "إضافة مراجعة",
  R.relation.name: "العلاقة",
  R.post.name: "نشر",
  R.orderEvent.name: "حدث الطلب",
  R.translatorCall.name: "اتصال المترجم",
  R.newPostComment.name: "تعليق جديد",
  R.newPostLike.name: "إعجاب جديد",
  R.newCommentReply.name: "رد جديد",
  R.friendRequest.name: "طلب صداقة",
  R.friendRequestAccepted.name: "تم قبول طلب الصداقة",
  R.newFollow.name: "اشتراك جديدة",
  R.newSwapItemReview.name: "مراجعة مبادلة جديدة",
  R.newSwapItemLike.name: "إعجاب جديد",
  R.addFirstPost.name: "جديد في Fibali! شارك الآخرين بما يدور في بالك.",
  R.newPost.name: "منشور جديد",
  R.privacyNSecurity.name: "الخصوصية والأمان",
  R.deleteAccount.name: "حذف الحساب",
  R.gallery.name: "المعرض",
  R.emptyNotificationsTitle.name: "لم يتم العثور على أي إشعارات",
  R.emptyNotificationsDescription.name: "ليس لديك أي إشعارات جديدة في الوقت الراهن",
  R.liked.name: "أعجبني",
  R.report.name: "الإبلاغ",
  R.lightMode.name: "وضع الإضاءة",
  R.brightness.name: "السطوع",
  R.termsOfService.name: "شروط الخدمة",
  R.skipLogging.name: "تخطي تسجيل الدخول",
  R.termsAndConditions.name: "الشروط والأحكام",
  R.iAgreeToTheTermsAndConditions.name: "أنا أوافق على الشروط والأحكام",
  R.viewTermsAndConditions.name: "عرض الشروط والأحكام",
  R.loggingIn.name: "تسجيل الدخول",
  R.askAgreeTermsConditions.name:
      "اهلا و سهلا!\\n\\nمرحبا بكم في فيبالي، التطبيق الجديد الذي يربطكم بأشخاص يرغبون في تبادل الأشياء التي لم يعدوا بحاجة إليها.\\n\\nقبل أن تبدأوا في التبادل، نحتاج منكم الموافقة على شروطنا وأحكامنا. هذه مجموعة من القواعد التي تحدد حقوقكم والالتزامات الخاصة بكم كمستخدمين لتطبيقنا. كما تتعامل مع قضايا هامة مثل حقوق الملكية الفكرية وإدارة النزاعات والسلوك المقبول.\\n\\nبالموافقة على شروطنا وأحكامنا ، فأنت تؤكد أنك قد قرأتها وفهمتها وتوافق على الالتزام بها. كما توافق على الامتثال لسياسة استخدامنا المقبولة ، التي يتم إدراجها عن طريق الإشارة إلى ذلك في شروطنا وأحكامنا.\\n\\nشروطنا وأحكامنا عقد قانوني ملزم بينك وبينا ، لذلك يرجى قراءتها بعناية. إذا كان لديك أي أسئلة أو مخاوف ، يرجى الاتصال بنا على piicubic@gmail.com. نحن سعداء لمساعدتك.\\n\\nلعرض شروطنا وأحكامنا ، يرجى النقر على الرابط أدناه. لقبولها والمتابعة باستخدام تطبيقنا ، يرجى تحديد الخانة والنقر فوق الزر أدناه。",
  R.place.name: "مكان",
  R.block.name: "حظر",
  R.blockUserDescription.name:
      "هل أنت متأكد من رغبتك في حظر هذا المستخدم؟ سيؤدي الحظر إلى منعهم بشكل دائم من التواصل معك أو عرض ملفك الشخصي. ومع ذلك، يمكنك إلغاء الحظر لاحقًا إذا قررت تغيير رأيك.",
  R.blockedUsers.name: "المستخدمون المحظورون",
  R.noBlockedUsers.name: "لا يوجد مستخدمون محظورون",
  R.oopsSomethingWentWrong.name: "عفوًا! حدث خطأ ما.",
  R.unBlockUserDescription.name:
      "هل أنت متأكد من رغبتك في إلغاء حظر هذا المستخدم؟ بمجرد إلغاء الحظر، سيتمكنون من التواصل معك وعرض ملفك الشخصي مرة أخرى.",
  R.userNotFound.name: "المستخدم غير موجود",
  R.blockedAt.name: "تم الحظر في",
  R.youHaveBeenBlockedByThisUser.name: "تم حظرك من قبل هذا المستخدم.",
  R.youHaveBlockedThisUser.name: "لقد قمت بحظر هذا المستخدم.",
  R.storeNotFound.name: "المتجر غير موجود",
  R.storeNotAvailable.name: "المتجر غير متاح",
  R.about.name: "حول",
  R.noPostHere.name: "لا توجد مشاركات هنا",
  R.whyNotShare.name: "لماذا لاتشارك ما يدور في ذهنك كي ترى ما يقوله الآخرون؟",
  R.followOtherUsersAndGetUpdated.name: "تابع المستخدمين الآخرين وتحصل على أحدث مشاركاتهم هنا",
  R.likedPostsWillAppearHere.name: "المنشورات التي قمت بالإعجاب بها ستظهر هنا",
  R.commentedPostsWillAppearHere.name: "المنشورات التي قمت بالتعليق عليها ستظهر هنا ",
  R.swapIntroDescription.name: "إكتشف و استبدل الأغراض التي لا تحتاجها بأخرى تريدها بضغطة زر",
  R.connectIntroDescription.name:
      "تبادل الأغراض و تبادل الأفكار، شارك ما في بالك و تعرف على اناس جدد",
  R.fashion.name: "موضة",
  R.beauty.name: "جمال",
  R.travel.name: "سفر",
  R.family.name: "عائلة",
  R.health.name: "صحة",
  R.fitness.name: "لياقة بدنية",
  R.music.name: "موسيقى",
  R.movies.name: "أفلام",
  R.specialEvents.name: "مناسبات خاصة",
  R.hobbies.name: "هوايات",
  R.technology.name: "تكنولوجيا",
  R.homeDecor.name: "ديكور المنزل",
  R.dIY.name: "افعلها بنفسك",
  R.gardening.name: "بستنة",
  R.finance.name: "تمويل",
  R.studentLife.name: "حياة الطالب",
  R.pets.name: "حيوانات أليفة",
  R.currentNews.name: "الأخبار الحالية",
  R.science.name: "علم",
  R.newUpdateAvailableTitle.name: "تحديث جديد متاح",
  R.newUpdateAvailableDescription.name:
      "لدينا نسخة جديدة متاحة لك للتحميل. يرجى التحديث الصدار للاستمتاع بأحدث الميزات والتحسينات.",
  R.notification.name: "إشعار",
  R.swipeRightDescription.name:
      "السحب اعلان إلى اليمين يعني أنك تحبه. إذا أحب صاحب الاعلان احد أغراضك، فسيتم مطابقتكم للتبادل.",
  R.swipeLeftDescription.name:
      "السحب اعلان إلى اليسار يعني أنك لست مهتمًا به. لن ترى هذا اعلان مرة أخرى.",
  R.noChatsYetTitle.name: "لا توجد دردشة بعد",
  R.noChatsYetDescription.name: "أضف أصدقاء جدد وابدأ الدردشة",
  R.whoCanMyPost.name: "من يمكنه رؤية منشوري؟",
  R.comment.name: "تعليق",
  R.needToLogin.name: "يجب عليك تسجيل الدخول للمتابعة",
  R.finishSwipingToSeeMore.name: "اسحب جميع الاعلانات لرؤية المزيد",
  R.pleaseAllowAccessToGPSLocation.name:
      " معرفة موقعك الحالي اساسي من اجل ايجاد الاعلانات الاقرب اليك",
  R.addPrice.name: "اضف السعر",
  R.deleteItemWarning.name: "هل انت متأكد من حذف هذا الاعلان؟",
  R.cantReachNetwork.name: "لا يمكن الوصول إلى الشبكة",
  R.pleaseCheckYourNetworkNTryAgain.name: "يرجى التحقق من اتصالك بالشبكة والمحاولة مرة أخرى",
  R.noInternetConnection.name: "لا يوجد اتصال بالإنترنت",
  R.viewedPostsWillAppearHere.name: "المنشورات التي قمت بمشاهدتها ستظهر هنا",
  R.swapsWillAppearHere.name: "التبادلات التي قمت بها ستظهر هنا",
  R.noComments.name: "لا توجد تعليقات",
  R.readMore.name: "اقرأ أكثر",
  R.showLess.name: "أظهر أقل",
  R.startingLiveVideo.name: "بدء البث المباشر",
  R.liveVideoStarted.name: "بدأ البث المباشر",
  R.liveIsAlreadyStarting.name: "البث المباشر قيد التهيئة",
  R.startLiveStreaming.name: "بدء بث المباشر",
  R.myStores.name: "متاجر",
  R.stores.name: "متاجر",
  R.catalog.name: "كتالوج",
  R.postNotFound.name: "المنشور غير موجود",
  R.cantOpen.name: "لا يمكن فتح",
  R.remove.name: "إزالة",
  R.sevenDayReturnPolicy.name: "حق الإرجاع خلال 7 أيام",
  R.fourteenDayReturnPolicy.name: "حق الإرجاع خلال 14 يوم",
  R.thirtyDayReturnPolicy.name: "حق الإرجاع خلال 30 يوم",
  R.sixtyDayReturnPolicy.name: "حق الإرجاع خلال 60 يوم",
  R.ninetyDayReturnPolicy.name: "حق الإرجاع خلال 90 يوم",
  R.noReturnPolicy.name: "لا يوجد حق إرجاع",
  R.sevenDayReturnPolicySellerDescription.name:
      "مثالية للسلع سريعة الاستهلاك أو ذات مدة صلاحية قصيرة. تمنح العملاء أسبوعاً كاملاً لإعادة المنتج إن لم يلبِ توقعاتهم.",
  R.fourteenDayReturnPolicySellerDescription.name:
      "مناسبة لسلع الاستهلاك السريع. توفر أسبوعين لإعادة المنتج إن لم يلبِ توقعاتك.",
  R.thirtyDayReturnPolicySellerDescription.name:
      "الأكثر شيوعاً. تمنح شهراً كاملاً لتقرير الاحتفاظ بالمنتج أو إعادته.",
  R.sixtyDayReturnPolicySellerDescription.name:
      "أقل شيوعاً، تستخدم للمنتجات عالية القيمة التي قد تحتاج إلى وقت أطول لتقييمها.",
  R.ninetyDayReturnPolicySellerDescription.name:
      "سخية، تستخدمها الشركات الواثقة من منتجاتها. يمكن أن تكون نقطة بيع قوية للعملاء.",
  R.noReturnPolicySellerDescription.name:
      " المنتج نهائي ولا يمكن إعادته. مناسبة للمنتجات التي لا يمكن إعادة بيعها لأسباب صحية أو النظافة، أو المنتجات المصممة حسب الطلب، أو المنتجات المخفضة.",
  R.sevenDayReturnPolicyBuyerDescription.name:
      "يمكنك إرجاع هذا المنتج خلال 7 أيام لاسترداد كامل المبلغ.",
  R.fourteenDayReturnPolicyBuyerDescription.name:
      "يمكنك إرجاع هذا المنتج خلال 14 يومًا لاسترداد كامل المبلغ.",
  R.thirtyDayReturnPolicyBuyerDescription.name:
      "يمكنك إرجاع هذا المنتج خلال 30 يومًا لاسترداد كامل المبلغ.",
  R.sixtyDayReturnPolicyBuyerDescription.name:
      "يمكنك إرجاع هذا المنتج خلال 60 يومًا لاسترداد كامل المبلغ.",
  R.ninetyDayReturnPolicyBuyerDescription.name:
      "يمكنك إرجاع هذا المنتج خلال 90 يومًا لاسترداد كامل المبلغ.",
  R.noReturnPolicyBuyerDescription.name: "هذا المنتج غير قابل للإرجاع.",
  R.defectiveOrDamaged.name: "معيب أو تالف",
  R.defectiveOrDamagedSellerDescription.name:
      "تسمح هذه السياسة بإرجاع المنتجات التي وصلت معيبةً أو ظهر فيها عيبٌ في فترة استخدام معقولة. تشمل عيوب التصنيع وأضرار الشحن والأعطال التي تحدث أثناء الاستخدام العادي. هذا يحمي المشترين من أن يعلقوا بمنتجات معيبة.",
  R.defectiveOrDamagedBuyerDescription.name:
      "يمكنك إرجاع هذا المنتج إذا كان معيبًا أو تالفًا. يشمل ذلك المنتجات التي وصلت مع عيوب أو ظهرت فيها مشاكل خلال وقت معقول من الاستخدام أو تضررت أثناء الشحن. يرجى تقديم تفاصيل حول العيب أو التلف عند طلب الإرجاع.",
  R.notAsDescribed.name: "غير مطابق للوصف",
  R.notAsDescribedSellerDescription.name:
      "تسمح هذه السياسة بإرجاع المنتجات التي تختلف بشكل كبير عن وصفها أو ميزاتها المعلن عنها. تشمل التناقضات في الحجم واللون والوظائف أو غيرها من الخصائص الأساسية. هذا يحمي المشترين من المعلومات المضللة أو غير الدقيقة عن المنتج.",
  R.notAsDescribedBuyerDescription.name:
      "يمكنك إرجاع هذا المنتج إذا لم يكن مطابقًا للوصف في القائمة. يشمل ذلك المنتجات التي تختلف في الحجم أو اللون أو الميزات أو الجوانب المهمة الأخرى مقارنة بوصف المنتج. يرجى تقديم تفاصيل حول التناقضات عند طلب الإرجاع.",
  R.unusedAndInOriginalCondition.name: "غير مستخدم وفي الحالة الأصلية",
  R.unusedAndInOriginalConditionSellerDescription.name:
      "هذه سياسة قياسية تضمن إعادة المنتجات في نفس الحالة التي تم استلامها فيها. تنطبق عادةً على المنتجات غير المفتوحة أو المنتجات ذات الأختام غير المكسورة أو المنتجات التي لا تظهر عليها أي علامات تآكل أو استخدام. هذا يحمي البائعين من قبول المنتجات المستعملة أو التالفة للإرجاع.",
  R.unusedAndInOriginalConditionBuyerDescription.name:
      "يجب إعادة المنتج في حالته الأصلية وعبوته. يجب أن يكون غير مفتوح وغير مستخدم وبجميع العلامات والعلامات الأصلية سليمة. يرجى التأكد من تعبئة المنتج بعناية لتجنب التلف أثناء إعادة الشحن.",
  R.inStoreExchanges.name: "الاستبدال في المتجر",
  R.inStoreExchangesSellerDescription.name: "السماح للعملاء باستبدال منتجهم بمنتج آخر في متجرك.",
  R.mailExchanges.name: "الاستبدال عبر البريد",
  R.mailExchangesSellerDescription.name: "السماح للعملاء بإرسال منتجهم إليك بالبريد للاستبدال.",
  R.homeOfficeExchanges.name: "الاستبدال في المنزل أو المكتب",
  R.homeOfficeExchangesSellerDescription.name:
      "ترتيب قيام ساعي بجمع المنتج مباشرة من عنوان العميل للاستبدال.",
  R.shared.name: "تشارك",
  R.returnPolicy.name: "سياسة الإرجاع",
  R.returnPolicyDescription.name:
      "توضح سياسة الإرجاع للعملاء عدد الأيام التي لديهم لإعادة المنتج واسترداد الأموال.",
  R.chooseReturnTimeFrame.name: "اختيار سياسة الإرجاع",
  R.acceptExchange.name: "قبول الاستبدالات",
  R.acceptExchangeDescription.name:
      "حدد كيف يمكن للعملاء استبدال المنتجات. يمكنك اختيار خيار واحد أو أكثر.",
  R.conditions.name: 'الشروط',
  R.conditionsDescription.name: 'حدد الشروط التي يجب أن يستوفيها المنتج ليُصبح مؤهلاً للإرجاع.',
  R.noMoreProducts.name: "لا يوجد المزيد من المنتجات",
  R.global.name: "عالمي",
};

// generate string asking user to give camera library permisision and a detailed account on how it is going to be used by the app for swaps or sharing posts
// string: "We need your permission to access your camera and photo library to take photos and share them with other users."
